# -*- coding: utf-8 -*-
"""第四课 · 词汇搭配库与高分例句库。

选词原则：只收"舒同学课上蹦得出中文、但写不出英文"的那一类。
每条都给中式陷阱，因为她的问题不是不认识词，是搭配错。
"""

# ============================================================ 词汇搭配库
# (中文, 英文搭配, 中式陷阱 / 用法提示, 例句)
COLLOCATIONS = [

("教育 Education", [
 ("拓宽视野", "broaden one's horizons",
  "✗ widen one's eyes／open one's view", "Studying abroad broadens students' horizons."),
 ("培养批判性思维", "cultivate critical thinking",
  "cultivate / foster / develop 都可，别用 train", "Universities should cultivate critical thinking, not obedience."),
 ("打下扎实基础", "lay a solid foundation for",
  "✗ build a strong base", "A broad curriculum lays a solid foundation for lifelong learning."),
 ("死记硬背", "rote learning / learn by rote",
  "✗ dead memory／hard back", "Rote learning produces high scores but little understanding."),
 ("减轻学业压力", "ease academic pressure",
  "ease / alleviate 比 reduce 更地道", "Cutting homework would ease academic pressure on teenagers."),
 ("因材施教", "tailor teaching to individual needs",
  "✗ teach according to material", "Small classes allow teachers to tailor teaching to individual needs."),
 ("学以致用", "apply what they have learned",
  "✗ use knowledge to practice", "Internships help students apply what they have learned."),
 ("就业前景", "employment prospects",
  "✗ work future", "A specialised degree may improve employment prospects."),
 ("适应不断变化的就业市场", "adapt to a changing job market",
  "✗ fit the change of job market", "Graduates must adapt to a rapidly changing job market."),
 ("具备扎实的专业知识", "have a solid grounding in a subject",
  "grounding 指打底的知识", "Employers value candidates with a solid grounding in statistics."),
 ("激发学习兴趣", "spark an interest in learning",
  "spark / stimulate，别用 cause", "Well-designed courses spark an interest in learning."),
 ("应试教育", "exam-oriented education",
  "✗ exam education", "Exam-oriented education leaves little room for creativity."),
 ("跟不上", "fall behind",
  "✗ can't follow up", "Students who miss the basics soon fall behind."),
 ("学术表现", "academic performance",
  "✗ study result", "Sleep deprivation harms academic performance."),
 ("终身学习", "lifelong learning",
  "固定说法，不加 -ing 之外的变体", "Technology has made lifelong learning far more accessible."),
 ("求知欲", "intellectual curiosity",
  "✗ desire of knowledge", "Intellectual curiosity matters more than memorised facts."),
 ("课外活动", "extracurricular activities",
  "✗ outside-class activities", "Extracurricular activities develop teamwork."),
 ("填鸭式教学", "spoon-feed students",
  "动词用法：spoon-feed sb", "Teachers who spoon-feed students discourage independent thought."),
 ("学费负担", "the burden of tuition fees",
  "✗ the pressure of study money", "Many families struggle with the burden of tuition fees."),
 ("综合素质", "all-round development",
  "✗ comprehensive quality", "Schools should aim at all-round development, not just grades."),
]),

("科技与媒体 Technology & Media", [
 ("沉迷于社交媒体", "be addicted to social media",
  "✗ indulge in／be crazy about", "Teenagers who are addicted to social media read far less."),
 ("注意力持续时间变短", "a shorter attention span",
  "✗ short attention time", "Constant notifications have produced a shorter attention span."),
 ("面对面交流", "face-to-face communication",
  "✗ face to face talk（要连字符作定语）", "Nothing replaces face-to-face communication."),
 ("削弱写作能力", "undermine writing skills",
  "undermine 比 weaken 更学术", "Predictive text may undermine writing skills."),
 ("依赖拼写检查", "rely on spell-checkers",
  "✗ depend on spelling check", "Students who rely on spell-checkers never learn to proofread."),
 ("信息过载", "information overload",
  "不可数，不加 s", "Information overload makes deep reading harder."),
 ("缩短距离", "bridge the distance",
  "✗ shorten the distance（物理距离才用）", "Video calls bridge the distance between families."),
 ("数字鸿沟", "the digital divide",
  "固定说法，必带 the", "The digital divide leaves rural pupils at a disadvantage."),
 ("保护隐私", "safeguard privacy",
  "✗ protect secret", "Stricter laws are needed to safeguard privacy online."),
 ("碎片化阅读", "fragmented reading",
  "✗ broken reading", "Fragmented reading discourages sustained concentration."),
 ("接触大量信息", "be exposed to a wealth of information",
  "✗ touch much information", "Young people are exposed to a wealth of information online."),
 ("取代传统媒体", "replace traditional media",
  "replace sth with sth，注意介词", "Streaming platforms have largely replaced traditional television."),
 ("虚假信息传播", "the spread of misinformation",
  "misinformation 不可数", "Social media accelerates the spread of misinformation."),
 ("提高效率", "boost efficiency",
  "boost / enhance 比 improve 更有力", "Automation has boosted efficiency in manufacturing."),
 ("屏幕使用时间", "screen time",
  "固定说法，不可数", "Paediatricians recommend limiting children's screen time."),
 ("网络欺凌", "cyberbullying",
  "一个词，不加空格", "Schools must take cyberbullying seriously."),
 ("随时随地", "at any time and in any place",
  "✗ anytime anywhere（口语）", "E-books can be read at any time and in any place."),
 ("双刃剑", "a double-edged sword",
  "整段只用一次，用滥会扣分", "Technology is a double-edged sword."),
 ("跟上技术变革", "keep pace with technological change",
  "✗ follow the technology", "Older workers struggle to keep pace with technological change."),
 ("降低成本", "cut costs",
  "✗ reduce the money", "Online courses cut costs for both universities and students."),
]),

("通用论证 Argument & Analysis", [
 ("归根结底", "in the final analysis",
  "放句首，后加逗号", "In the final analysis, the benefits outweigh the drawbacks."),
 ("从长远看", "in the long run",
  "✗ in the long future", "In the long run, prevention is cheaper than treatment."),
 ("就……而言", "when it comes to",
  "后接名词或动名词，不接从句", "When it comes to language learning, immersion works best."),
 ("起到关键作用", "play a pivotal role in",
  "pivotal / crucial / vital，别用 important role 到处套", "Parents play a pivotal role in early education."),
 ("对……产生深远影响", "have a profound impact on",
  "✗ give a deep influence to", "Automation has had a profound impact on employment."),
 ("权衡利弊", "weigh the pros and cons",
  "✗ balance the good and bad", "Policymakers must weigh the pros and cons carefully."),
 ("利大于弊", "the benefits outweigh the drawbacks",
  "outweigh 是及物动词，后面直接跟宾语", "For most families, the benefits outweigh the drawbacks."),
 ("达成共识", "reach a consensus",
  "✗ get the same idea", "Experts have yet to reach a consensus on this issue."),
 ("有充分理由认为", "there is good reason to believe that",
  "✗ there are many reasons to think", "There is good reason to believe that the trend will continue."),
 ("把资源投入到", "channel resources into",
  "✗ put money into（可用但偏口语）", "Governments should channel resources into public transport."),
 ("承担责任", "shoulder the responsibility",
  "✗ take the duty", "Individuals must also shoulder the responsibility for cutting waste."),
 ("解决根本原因", "tackle the root cause of",
  "✗ solve the basic reason", "Fines alone cannot tackle the root cause of pollution."),
 ("不可否认", "it is undeniable that",
  "后接完整句子", "It is undeniable that living standards have risen."),
 ("诚然……但是", "Admittedly, ... However, ...",
  "让步段的标准开头", "Admittedly, costs are high. However, the long-term savings are greater."),
 ("与其说……不如说", "less a matter of ... than of ...",
  "高级对比结构", "Success is less a matter of talent than of persistence."),
 ("这一现象可归因于", "This can be attributed to",
  "✗ This is because of（太简单）", "This can be attributed to rising living costs."),
 ("以……为代价", "at the expense of",
  "✗ with the price of", "Economic growth should not come at the expense of the environment."),
 ("采取切实措施", "take concrete steps",
  "✗ take real action", "Governments must take concrete steps to reduce emissions."),
 ("一小部分人", "a small minority",
  "✗ a few of people", "Only a small minority actually benefit from the policy."),
 ("与此形成对比的是", "By contrast,",
  "句首 + 逗号；in contrast 也可", "By contrast, rural schools receive far less funding."),
]),
]


# ========================================================== 高分例句库
# (功能, [(英文例句, 中文, 用法说明), ...])
MODEL_SENTENCES = [

("① 开头背景句", [
 ("The past two decades have witnessed a dramatic rise in the number of students choosing to study overseas.",
  "过去二十年，选择出国留学的学生人数急剧上升。",
  "「时间 + witness + 现象」——最好用的背景句模板，避免 With the development of..."),
 ("Few issues divide public opinion as sharply as the question of whether schools should abolish examinations.",
  "几乎没有哪个议题像“学校是否该取消考试”这样让舆论如此分裂。",
  "适合 discuss both views 开头，先点出争议性。"),
 ("As digital devices become embedded in everyday life, concerns have grown over their effect on young people.",
  "随着数字设备融入日常生活，人们越来越担心它对年轻人的影响。",
  "As 引导的背景状语，比 With the development of 高级得多。"),
 ("It is increasingly argued that universities should prioritise employability over academic depth.",
  "越来越多人主张，大学应把就业能力置于学术深度之上。",
  "It is argued that... 引出他人观点，天然中立。"),
]),

("② 表明立场 / 主旨句", [
 ("While both positions have merit, I am firmly of the view that a broad education serves students better.",
  "两种立场都有道理，但我坚定认为广博的教育对学生更有益。",
  "让步 + 立场，一句话完成 discuss both views 的表态。"),
 ("This essay will argue that the drawbacks of this trend are outweighed by its long-term benefits.",
  "本文将论证，这一趋势的弊端被其长期收益所抵消。",
  "被动的 outweigh，句式比 the advantages are more than 高级。"),
 ("In my view, the responsibility lies not with individuals alone but with governments as well.",
  "在我看来，责任不仅在个人，也在政府。",
  "not with A alone but with B as well——比 not only...but also 更书面。"),
 ("I would contend that the problem stems less from technology itself than from how it is used.",
  "我认为问题与其说源于技术本身，不如说源于使用方式。",
  "contend 比 think 有力；less from A than from B 是高分对比结构。"),
]),

("③ 让步与转折", [
 ("Admittedly, specialisation equips graduates with marketable skills; however, it narrows their intellectual range.",
  "诚然，专业化让毕业生具备市场需要的技能；然而这也窄化了他们的知识面。",
  "Admittedly...; however,... 是让步段的骨架，分号连接两个完整句。"),
 ("Although this argument appears convincing at first glance, it overlooks a crucial factor.",
  "尽管这一论点乍看令人信服，它却忽略了一个关键因素。",
  "反驳对方观点的万能句，后面接你要补的那个因素。"),
 ("Critics may object that such reforms are prohibitively expensive, yet the cost of inaction is higher still.",
  "批评者或许会反驳说这类改革成本过高，但不作为的代价更高。",
  "先替对方说话再推翻，是 7 分以上的标志。"),
 ("This is not to say that traditional methods are worthless; rather, they should be used selectively.",
  "这并不是说传统方法毫无价值；恰恰相反，它们应被有选择地使用。",
  "This is not to say that... rather... 用来防止观点被读成极端。"),
]),

("④ 因果论证", [
 ("An excessive focus on examination results leaves students little room to develop creativity.",
  "对考试成绩的过度关注，使学生几乎没有空间发展创造力。",
  "名词化主语（An excessive focus）+ leave sb little room to do——从 6 分到 7 分的关键句式。"),
 ("Because these skills are rarely assessed, schools have little incentive to teach them.",
  "由于这些能力很少被考核，学校几乎没有动力去教。",
  "Because 从句前置，主句给结果，因果链清晰。"),
 ("The consequence is a generation that can memorise efficiently but reason poorly.",
  "其结果是一代人擅长高效记忆，却不擅长推理。",
  "The consequence is + 名词短语，收束一段的漂亮写法。"),
 ("This in turn discourages young people from reading anything longer than a paragraph.",
  "这反过来又使年轻人不愿阅读超过一段的任何内容。",
  "in turn 表示连锁反应，专治“论证只有一层”。"),
]),

("⑤ 举例与让步举例", [
 ("Finland, for instance, abolished standardised testing yet consistently ranks among the top performers.",
  "例如芬兰取消了标准化考试，却始终位居成绩最好的国家之列。",
  "国名 + for instance 插入语，比 For example, 开头更灵活。"),
 ("A student who studies only engineering may design an efficient bridge but fail to ask whether it should be built.",
  "只学工程的学生也许能设计出高效的桥，却不会追问这座桥该不该建。",
  "具体到一个人的假设例子，比空泛的 many people 有力得多。"),
]),

("⑥ 结尾句", [
 ("In the final analysis, the aim of education should be to produce thinkers, not merely high scorers.",
  "归根结底，教育的目标应是培养思考者，而非仅仅是高分者。",
  "not merely A but B 的变体，结尾有力。"),
 ("Until these underlying causes are addressed, technological fixes will remain superficial.",
  "在这些深层原因得到解决之前，技术手段只能治标。",
  "Until 引导条件，给结尾留下行动方向。"),
 ("Balancing the two is therefore not a compromise but a necessity.",
  "因此，在两者之间取得平衡不是妥协，而是必需。",
  "not A but B，收尾干脆，适合 discuss both views。"),
]),
]
