# -*- coding: utf-8 -*-
"""Passage 2 · What Do Whales Feel? —— 逐题讲解内容（表格填空 + 简答题）。"""

MAP = [
    ("P1–P2", ["嗅觉：齿鲸没有", "味觉：神经退化", "触觉：其实很强"]),
    ("P3–P5", ["视觉因种而异", "立体视觉的方向", "栖息地决定视力"]),
    ("P6", ["听觉最发达", "低频 / 曲调式叫声", "齿鲸频谱更宽"]),
]

STRATEGY = [
    ("Q15–21 表格填空：表格是“原文顺序的地图”，先读行标题（SENSE/SPECIES）再回段。",),
    ("答案词数 NO MORE THAN THREE WORDS，先判断该填“物种名”还是“方向/频率”。",),
    ("Q22–26 简答题：题干疑问词决定答案词性——Which sense→感官名，Which species→物种名。",),
]

SUMMARY = [
    ("表格题动作", ["按行找段", "按列定词性", "抄原文形式"]),
    ("易错点", ["baleen vs toothed", "forward and downward", "复数 waters"]),
    ("简答题", ["疑问词定词性", "≤3 词", "不改写原文"]),
]

Q = [
 # ------------------------------------------------------------------ Q15
 dict(n=15, kind="TABLE",
   title="P2 Q15｜Taste 行：神经连接的是什么",
   stem="Taste｜some types｜poor｜nerves linked to their 15 …………… are underdeveloped",
   entry=["nerves linked to their + 空格 → 名词。", "锚点：Taste（味觉）。"],
   ev="P1 S5: Similarly, although at least some cetaceans have taste buds, the nerves serving these have "
      "degenerated or are rudimentary.",
   logic=["linked to ↔ serving（连接／服务于）。",
          "underdeveloped ↔ degenerated or are rudimentary（退化、发育不全）。",
          "these 回指 taste buds，把代词还原就是答案。"],
   ans="taste buds", ansnote=["两词，符合≤3词。", "代词还原题。"],
   stitle="P2 Q15｜although 让步 + these 的回指",
   sent="Similarly, although at least some cetaceans have taste buds, the nerves serving these have "
        "degenerated or are rudimentary.",
   core="The nerves have degenerated or are rudimentary.",
   layers=["although ... 是让步从句：有味蕾。",
           "主句主语 the nerves，谓语 have degenerated / are。",
           "serving these 是现在分词后置定语，修饰 nerves。",
           "these = taste buds，这是本题的答案来源。"],
   cn="同样，尽管至少有些鲸类拥有味蕾，但为这些味蕾服务的神经已经退化或发育不全。",
   vocab=["degenerate 退化 ↔ deteriorate；rudimentary 未发育的 ↔ underdeveloped",
          "serve = be linked to（此处指神经连接）"]),
 # ------------------------------------------------------------------ Q16
 dict(n=16, kind="TABLE",
   title="P2 Q16｜Vision 行：谁没有立体视觉",
   stem="Vision｜16 ……………｜yes｜probably do not have stereoscopic vision",
   entry=["空格在 SPECIES 列 → 填物种名。", "锚点：do not have stereoscopic vision。"],
   ev="P3 S3: However, the position of the eyes so restricts the field of vision in baleen whales that they "
      "probably do not have stereoscopic vision.",
   logic=["表格 COMMENTS 与原文后半句逐词对应。",
          "so ... that 结果状语从句里的主语就是答案主体。",
          "in baleen whales → 填 baleen whales。"],
   ans="baleen whales", ansnote=["也可写 baleen species。", "≤3 词。"],
   stitle="P2 Q16｜so ... that 结果状语从句",
   sent="However, the position of the eyes so restricts the field of vision in baleen whales that they "
        "probably do not have stereoscopic vision.",
   core="The position of the eyes restricts the field of vision.",
   layers=["主语是 the position of the eyes，不是 whales。",
           "so + 动词 ... that ... 是“如此……以至于……”。",
           "that 从句是结果，表格考的正是这个结果。",
           "they 回指 baleen whales。"],
   cn="然而，眼睛的位置极大地限制了须鲸的视野，以至于它们很可能没有立体视觉。",
   vocab=["restrict 限制 ↔ limit；field of vision 视野",
          "stereoscopic vision 立体视觉；baleen 须鲸的"]),
 # ------------------------------------------------------------------ Q17
 dict(n=17, kind="TABLE",
   title="P2 Q17｜海豚与鼠海豚的立体视觉方向",
   stem="dolphins, porpoises｜yes｜probably have stereoscopic vision 17 …………… and ……………",
   entry=["空格填方向词，两个并列。", "锚点：dolphins, porpoises。"],
   ev="P4 S1: On the other hand, the position of the eyes in most dolphins and porpoises suggests that they "
      "have stereoscopic vision forward and downward.",
   logic=["表格物种与原文 most dolphins and porpoises 对应。",
          "stereoscopic vision 后直接跟方向词。",
          "照抄 forward and downward，注意不要与下一行的 upward 混。"],
   ans="forward and downward", ansnote=["三词，刚好≤3。", "别写成 upward。"],
   stitle="P2 Q17｜suggests that 引出推断",
   sent="On the other hand, the position of the eyes in most dolphins and porpoises suggests that they have "
        "stereoscopic vision forward and downward.",
   core="The position of the eyes suggests that they have stereoscopic vision.",
   layers=["On the other hand 表示与上段须鲸对比。",
           "主语仍是 the position of the eyes。",
           "suggests that ... 是宾语从句，内容是推断结论。",
           "forward and downward 是方向状语，本题考点。"],
   cn="另一方面，大多数海豚和鼠海豚的眼睛位置表明，它们拥有向前和向下的立体视觉。",
   vocab=["porpoise 鼠海豚；suggest 表明 ↔ indicate / imply",
          "forward and downward 向前和向下"]),
 # ------------------------------------------------------------------ Q18
 dict(n=18, kind="TABLE",
   title="P2 Q18｜向前向上立体视觉属于哪一类",
   stem="18 ……………｜yes｜probably have stereoscopic vision forward and upward",
   entry=["空格在 SPECIES 列 → 物种名。", "锚点：forward and upward。"],
   ev="P4 S2: Eye position in freshwater dolphins, which often swim on their side or upside down while "
      "feeding, suggests that what vision they have is stereoscopic forward and upward.",
   logic=["用 forward and upward 反向定位，一句命中。",
          "该句主语是 Eye position in freshwater dolphins。",
          "填 freshwater dolphins，不能只写 dolphins（会与上一行混）。"],
   ans="freshwater dolphins", ansnote=["必须带 freshwater。", "两词。"],
   stitle="P2 Q18｜which 非限定定从 + what 名词性从句",
   sent="Eye position in freshwater dolphins, which often swim on their side or upside down while feeding, "
        "suggests that what vision they have is stereoscopic forward and upward.",
   core="Eye position suggests that their vision is stereoscopic forward and upward.",
   layers=["which ... feeding 是插入的非限定定语从句，先盖住。",
           "盖住后主干立刻显形：Eye position suggests that ...。",
           "what vision they have 是 that 从句里的主语（名词性从句）。",
           "while feeding 是时间状语，Q23 会再用到。"],
   cn="淡水海豚的眼睛位置表明，它们所具有的视觉是向前和向上的立体视觉；它们进食时常侧游或倒着游。",
   vocab=["freshwater 淡水的；upside down 上下颠倒地",
          "feed 进食 ↔ eat；on their side 侧着身体"]),
 # ------------------------------------------------------------------ Q19
 dict(n=19, kind="TABLE",
   title="P2 Q19｜宽吻海豚在哪种介质中视力出众",
   stem="bottlenose dolphins｜yes｜exceptional in 19 …………… and good in air-water interface",
   entry=["exceptional in + 空格 → 名词。", "与后半句 air-water interface 并列。"],
   ev="P4 S3: By comparison, the bottlenose dolphin has extremely keen vision in water.",
   logic=["exceptional ↔ extremely keen（极其敏锐）。",
          "in + 空格 与原文 in water 完全对应。",
          "答案就是 water，一词即可。"],
   ans="water", ansnote=["ONE WORD 足够。", "别写 in water。"],
   stitle="P2 Q19｜By comparison 的对比信号",
   sent="By comparison, the bottlenose dolphin has extremely keen vision in water. Judging from the way it "
        "watches and tracks airborne flying fish, it can apparently see fairly well through the air-water "
        "interface as well.",
   core="The bottlenose dolphin has extremely keen vision in water.",
   layers=["By comparison 提示：与前面几种海豚做对比。",
           "第一句是水中视力，第二句是水气交界视力。",
           "表格把两句压成一行，所以要连读两句。",
           "Judging from ... 是分词状语，表判断依据。"],
   cn="相比之下，宽吻海豚在水中视力极其敏锐。从它观察并追踪空中飞鱼的方式判断，它显然也能较好地透过水气交界面看东西。",
   vocab=["keen 敏锐的 ↔ sharp / exceptional；airborne 空中的",
          "by comparison 相比之下；interface 交界面"]),
 # ------------------------------------------------------------------ Q20
 dict(n=20, kind="TABLE",
   title="P2 Q20｜大型须鲸主要使用什么",
   stem="most large baleen｜yes｜usually use 20 ……………; repertoire limited",
   entry=["usually use + 空格 → 名词。", "锚点：Hearing 行 + large baleen。"],
   ev="P6 S3: Large baleen whales primarily use the lower frequencies and are often limited in their repertoire.",
   logic=["usually ↔ primarily（主要地）。",
          "repertoire limited ↔ are often limited in their repertoire。",
          "取 use 的宾语：lower frequencies，注意复数。"],
   ans="lower frequencies", ansnote=["两词，保留复数。", "比较级 lower 不能丢。"],
   stitle="P2 Q20｜and 并列两个谓语",
   sent="Large baleen whales primarily use the lower frequencies and are often limited in their repertoire.",
   core="Large baleen whales use the lower frequencies and are limited in their repertoire.",
   layers=["一个主语带两个并列谓语：use ... and are ...。",
           "primarily / often 是频率副词，对应表格的 usually。",
           "lower 是比较级，隐含“比齿鲸低”。",
           "repertoire 指“声音种类的范围”。"],
   cn="大型须鲸主要使用较低的频率，而且其发声种类往往有限。",
   vocab=["primarily 主要地 ↔ mainly / usually；repertoire 曲目、声音范围",
          "frequency 频率（复数 frequencies）"]),
 # ------------------------------------------------------------------ Q21
 dict(n=21, kind="TABLE",
   title="P2 Q21｜哪种鲸的叫声近乎歌唱",
   stem="21 …………… whales and …………… whales｜yes｜song-like",
   entry=["空格 + whales → 物种前缀名。", "锚点：song-like（近似歌唱）。"],
   ev="P6 S4: Notable exceptions are the nearly song-like choruses of bowhead whales in summer and the "
      "complex, haunting utterances of the humpback whales.",
   logic=["song-like ↔ nearly song-like choruses，一词命中。",
          "原表印作 bowhead whales and humpback whales。",
          "编号空 21 只考第一个：bowhead。"],
   ans="bowhead", ansnote=["ONE WORD。", "第二处为 humpback（非考点）。"],
   stitle="P2 Q21｜Notable exceptions are ... 的表语并列",
   sent="Notable exceptions are the nearly song-like choruses of bowhead whales in summer and the complex, "
        "haunting utterances of the humpback whales.",
   core="Notable exceptions are the choruses of bowhead whales and the utterances of humpback whales.",
   layers=["exceptions 指“上一句 limited repertoire 的例外”。",
           "are 后面是两个并列的名词短语作表语。",
           "of bowhead whales / of the humpback whales 是所属修饰。",
           "先找 and 两边的对称结构，答案自然浮现。"],
   cn="值得注意的例外是弓头鲸夏季近乎歌唱的合唱，以及座头鲸复杂而萦绕人心的鸣叫。",
   vocab=["chorus 合唱 ↔ song-like sounds；utterance 发声 ↔ sound / call",
          "notable exception 显著的例外；haunting 萦绕人心的"]),
 # ------------------------------------------------------------------ Q22
 dict(n=22, kind="SHORT",
   title="P2 Q22｜哪种感官与求偶有关",
   stem="Which of the senses is described here as being involved in mating?",
   entry=["Which sense → 答案是感官名词。", "锚点：mating（交配／求偶）。"],
   ev="P2 S3: This contact may help to maintain order within a group, and stroking or touching are part of "
      "the courtship ritual in most species.",
   logic=["mating ↔ courtship ritual（求偶仪式）。",
          "该句主语是 stroking or touching，属于触觉。",
          "答案写感官名 touch，不要抄 stroking。"],
   ans="touch", ansnote=["ONE WORD。", "写感官名，不写动作。"],
   stitle="P2 Q22｜and 并列两个功能",
   sent="This contact may help to maintain order within a group, and stroking or touching are part of the "
        "courtship ritual in most species.",
   core="Stroking or touching are part of the courtship ritual.",
   layers=["and 前讲“维持群体秩序”，and 后讲“求偶”。",
           "题干只问求偶，所以只取 and 之后。",
           "stroking or touching 是并列动名词主语。",
           "in most species 是范围限定，不影响答案。"],
   cn="这种接触可能有助于维持群体内部秩序，而抚摸或触碰在多数物种中是求偶仪式的一部分。",
   vocab=["courtship 求偶 ↔ mating behaviour；stroke 抚摸",
          "maintain order 维持秩序；ritual 仪式"]),
 # ------------------------------------------------------------------ Q23
 dict(n=23, kind="SHORT",
   title="P2 Q23｜哪种海豚进食时倒着游",
   stem="Which species swims upside down while eating?",
   entry=["Which species → 答案是物种名。", "锚点：upside down + eating。"],
   ev="P4 S2: Eye position in freshwater dolphins, which often swim on their side or upside down while "
      "feeding, suggests that ...",
   logic=["eating ↔ feeding（进食）。",
          "upside down 原词复现，直接锁定定语从句。",
          "从句修饰的主体是 freshwater dolphins。"],
   ans="freshwater dolphins", ansnote=["两词。", "与 Q18 同句不同考点。"],
   stitle="P2 Q23｜同一句的第二个考点：定语从句内部信息",
   sent="Eye position in freshwater dolphins, which often swim on their side or upside down while feeding, "
        "suggests that what vision they have is stereoscopic forward and upward.",
   core="Freshwater dolphins often swim upside down while feeding.",
   layers=["Q18 考的是主句 suggests 的内容。",
           "Q23 考的是插入的定语从句本身。",
           "同一个长句可以出两道题——这就是拆句的价值。",
           "which 的先行词是 freshwater dolphins。"],
   cn="淡水海豚常常侧游或倒着游进食，它们的眼睛位置表明其视觉是向前向上的立体视觉。",
   vocab=["feeding = eating；upside down 倒置地",
          "先行词 antecedent：which 指代 freshwater dolphins"]),
 # ------------------------------------------------------------------ Q24
 dict(n=24, kind="SHORT",
   title="P2 Q24｜宽吻海豚能从水下追踪什么",
   stem="What can bottlenose dolphins follow from under the water?",
   entry=["What → 答案是名词。", "锚点：bottlenose + from under the water。"],
   ev="P4 S4: Judging from the way it watches and tracks airborne flying fish, it can apparently see fairly "
      "well through the air-water interface as well.",
   logic=["follow ↔ tracks（追踪）。",
          "from under the water ↔ through the air-water interface。",
          "取 tracks 的宾语：(airborne) flying fish。"],
   ans="(airborne) flying fish", ansnote=["≤3 词。", "airborne 可写可不写。"],
   stitle="P2 Q24｜Judging from 分词状语引出证据",
   sent="Judging from the way it watches and tracks airborne flying fish, it can apparently see fairly well "
        "through the air-water interface as well.",
   core="It can see fairly well through the air-water interface.",
   layers=["Judging from ... 是分词状语，说明“依据什么判断”。",
           "the way (that) it watches and tracks ... 是方式定语从句。",
           "主句主语 it 指 the bottlenose dolphin。",
           "答案藏在状语里，不在主句里。"],
   cn="从它观察并追踪空中飞鱼的方式判断，它显然也能较好地透过水气交界面看东西。",
   vocab=["track 追踪 ↔ follow；airborne 在空中的",
          "judging from 根据……判断"]),
 # ------------------------------------------------------------------ Q25
 dict(n=25, kind="SHORT",
   title="P2 Q25｜哪种栖息地对应良好视力",
   stem="Which type of habitat is related to good visual ability?",
   entry=["Which habitat → 答案是环境名词。", "锚点：habitat + good vision。"],
   ev="P5 S2: For example, vision is obviously more useful to species inhabiting clear open waters than to "
      "those living in turbid rivers and flooded plains.",
   logic=["good visual ability ↔ vision is more useful（比较级的高端）。",
          "more useful to A than to B：A＝clear open waters。",
          "比较方向决定取哪一边，别抄 turbid rivers。"],
   ans="clear open waters", ansnote=["三词，保留复数。", "取比较级“高”的一端。"],
   stitle="P2 Q25｜more useful to A than to B 的方向",
   sent="For example, vision is obviously more useful to species inhabiting clear open waters than to those "
        "living in turbid rivers and flooded plains.",
   core="Vision is more useful to species inhabiting clear open waters.",
   layers=["more ... than 把两类栖息地放在天平两端。",
           "inhabiting / living 都是现在分词后置定语。",
           "those = species，回指前面的名词。",
           "画 clear open waters > turbid rivers，答案即定。"],
   cn="例如，视觉显然对栖息于清澈开阔水域的物种更有用，而对生活在浑浊河流和泛滥平原中的物种用处较小。",
   vocab=["inhabit 栖息于 ↔ live in；turbid 浑浊的 ↔ muddy / cloudy",
          "flooded plains 泛滥平原；habitat 栖息地"]),
 # ------------------------------------------------------------------ Q26
 dict(n=26, kind="SHORT",
   title="P2 Q26｜鲸类哪种感官最发达",
   stem="Which of the senses is best developed in cetaceans?",
   entry=["Which sense → 感官名词。", "锚点：best developed（最发达）。"],
   ev="P6 S1: Although the senses of taste and smell appear to have deteriorated, and vision in water appears "
      "to be uncertain, such weaknesses are more than compensated for by cetaceans' well-developed acoustic sense.",
   logic=["best developed ↔ well-developed。",
          "Although 之前是弱项，之后才是强项。",
          "acoustic sense ＝ 听觉，答案写 hearing 或 acoustic sense。"],
   ans="hearing / acoustic sense", ansnote=["两种写法均可。", "≤3 词。"],
   stitle="P2 Q26｜Although 让步把“弱”与“强”分开",
   sent="Although the senses of taste and smell appear to have deteriorated, and vision in water appears to "
        "be uncertain, such weaknesses are more than compensated for by cetaceans' well-developed acoustic sense.",
   core="Such weaknesses are compensated for by their well-developed acoustic sense.",
   layers=["Although 引导的让步从句里有两个并列分句（味嗅觉、视觉）。",
           "主句从 such weaknesses 开始，才是重点。",
           "be compensated for by ... 是被动＋介词，by 后是“补偿者”。",
           "more than compensated ＝ 不止补偿，绰绰有余。"],
   cn="尽管味觉和嗅觉似乎已退化、水中视觉也不确定，但这些弱点被鲸类高度发达的听觉充分弥补了。",
   vocab=["deteriorate 退化 ↔ get worse；compensate for 弥补 ↔ make up for",
          "acoustic 听觉的 ↔ hearing；well-developed 发达的"]),
]
