# -*- coding: utf-8 -*-
"""Passage 3 · Visual Symbols and the Blind —— 逐题讲解内容（选择 + 图形配对 + 词库摘要）。"""

MAP = [
    ("Part 1 · P1–P3", ["盲人能懂轮廓与透视", "盲女画出运动线", "五种轮辐实验设计"]),
    ("Part 1 · P4–P5", ["五种轮辐 → 五种运动", "明眼人与盲人首选一致", "共识度几乎相同"]),
    ("Part 2 · P6–P8", ["圆/方与20组词", "51% 只在 deep-shallow", "结论：理解方式相同"]),
]

STRATEGY = [
    ("Q27–29、Q40 选择题：题干先划限定（first paragraph / surprised / Part 1），再回原文找唯一句。",),
    ("Q30–32 图形配对：先把五种轮辐画法与五种运动在原文里配好，再看图选。",),
    ("Q33–39 词库摘要：先判断每个空的词性与单复数，再从词库里挑；同一个词可以重复使用。",),
]

SUMMARY = [
    ("选择题", ["题干限定优先", "找唯一支持句", "别选“太强”的选项"]),
    ("图形配对", ["先配原文", "再看图", "五配三有干扰"]),
    ("词库摘要", ["先定词性", "可重复使用", "数字回原文核对"]),
]

Q = [
 # ------------------------------------------------------------------ Q27
 dict(n=27, kind="MCQ",
   title="P3 Q27｜第一段对盲人下了什么结论",
   stem="In the first paragraph the writer makes the point that blind people",
   options=["may be interested in studying art.", "can draw outlines of different objects and surfaces.",
            "can recognise conventions such as perspective.", "can draw accurately."],
   entry=["限定：the first paragraph。", "只在 P1 找作者的“论点句”。"],
   ev="P1 S1: ... it has become clear that blind people can appreciate the use of outlines and perspectives "
      "to describe the arrangement of objects and other surfaces in space.",
   logic=["appreciate the use of outlines and perspectives ＝ 能理解这些惯例。",
          "原文说的是“理解/欣赏”，不是“画得准” → B、D 排除。",
          "学艺术兴趣未提 → A 排除。perspective 原词复现 → C。"],
   ans="C", ansnote=["recognise conventions", "appreciate = recognise"],
   stitle="P3 Q27｜it has become clear that ... 形式主语",
   sent="From a number of recent studies, it has become clear that blind people can appreciate the use of "
        "outlines and perspectives to describe the arrangement of objects and other surfaces in space.",
   core="It has become clear that blind people can appreciate outlines and perspectives.",
   layers=["From ... studies 是来源状语，先跳过。",
           "it 是形式主语，真主语是 that 从句。",
           "从句主干：blind people can appreciate the use of ...。",
           "to describe ... 是目的状语，说明这些手法的用途。"],
   cn="从近来的一些研究可以清楚看出，盲人能够理解用轮廓和透视来描述物体及其他表面在空间中排列的方式。",
   vocab=["appreciate 理解、领会 ↔ recognise / understand；outline 轮廓",
          "perspective 透视法 ＝ convention（绘画惯例）"]),
 # ------------------------------------------------------------------ Q28
 dict(n=28, kind="MCQ",
   title="P3 Q28｜作者为什么感到吃惊",
   stem="The writer was surprised because the blind woman",
   options=["drew a circle on her own initiative.", "did not understand what a wheel looked like.",
            "included a symbol representing movement.", "was the first person to use lines of motion."],
   entry=["锚点：surprised ↔ I was taken aback。", "找“吃惊”前后各一句。"],
   ev="P1 S3–S6: ... decided on her own initiative to draw a wheel as it was spinning. To show this motion, "
      "she traced a curve inside the circle. I was taken aback. Lines of motion ... are a very recent invention.",
   logic=["她画的是 a curve to show this motion ＝ 表示运动的符号。",
          "吃惊的原因是“运动线是很晚才出现的发明”，她却自发用了。",
          "D 说她是第一个使用者，原文只说这种线很新 → 过度推断。"],
   ans="C", ansnote=["symbol of movement", "运动线是新发明"],
   stitle="P3 Q28｜when 从句 + on her own initiative",
   sent="This fact was drawn to my attention dramatically when a blind woman in one of my investigations "
        "decided on her own initiative to draw a wheel as it was spinning.",
   core="This fact was drawn to my attention when a blind woman decided to draw a spinning wheel.",
   layers=["主句是被动：This fact was drawn to my attention。",
           "when 引导时间状语从句，讲具体事件。",
           "on her own initiative 是插入的介词短语：自发地。",
           "as it was spinning 又是一层时间状语。"],
   cn="当我研究中的一位盲人女性自发决定画一个正在旋转的轮子时，这一事实戏剧性地引起了我的注意。",
   vocab=["initiative 主动 ↔ of her own accord；taken aback 吃惊 ↔ surprised",
          "trace a curve 描出一条曲线；lines of motion 运动线"]),
 # ------------------------------------------------------------------ Q29
 dict(n=29, kind="MCQ",
   title="P3 Q29｜Part 1 实验得出什么发现",
   stem="From the experiment described in Part 1, the writer found that the blind subjects",
   options=["had good understanding of symbols representing movement.",
            "could control the movement of wheels very accurately.",
            "worked together well as a group in solving problems.",
            "got better results than the sighted undergraduates."],
   entry=["限定：Part 1 的实验结论。", "结论句在 P4–P5。"],
   ev="P4 S1: All but one of the blind subjects assigned distinctive motions to each wheel. "
      "P5 S4: ... the blind not only figured out meanings for each line of motion, but as a group they "
      "generally came up with the same meaning at least as frequently as did sighted subjects.",
   logic=["figured out meanings for each line of motion ＝ 理解了运动符号 → A。",
          "at least as frequently as ＝ 不低于，不是“更好” → D 排除。",
          "as a group 指统计口径，不是“合作解题” → C 排除。"],
   ans="A", ansnote=["good understanding", "figured out meanings"],
   stitle="P3 Q29｜not only ... but ... at least as ... as 的比较",
   sent="Evidently, however, the blind not only figured out meanings for each line of motion, but as a group "
        "they generally came up with the same meaning at least as frequently as did sighted subjects.",
   core="The blind figured out meanings and came up with the same meaning as frequently as sighted subjects.",
   layers=["not only ... but ... 并列两个谓语，都是盲人做到的事。",
           "as a group 是插入语，说明统计层面。",
           "at least as frequently as ＝ 至少和……一样频繁（＝不低于）。",
           "as did sighted subjects 是倒装的比较从句。"],
   cn="然而显然，盲人不仅弄清了每种运动线的含义，而且作为一个群体，他们得出相同含义的频率至少不低于明眼受试者。",
   vocab=["figure out 弄清 ↔ work out / understand；evidently 显然",
          "at least as ... as ＝ 不低于（不是“超过”）"]),
 # ------------------------------------------------------------------ Q30
 dict(n=30, kind="MATCH",
   title="P3 Q30｜轮辐伸出轮圈之外＝什么运动",
   stem="Diagram 30：轮辐为直线，且伸出轮圈之外（spokes extending beyond the rim）",
   entry=["先在原文找五种画法的对照。", "本图特征：超出轮圈。"],
   ev="P4 S3: Subjects assumed that spokes extending beyond the wheel's perimeter signified that the wheel "
      "had its brakes on and that dashed spokes indicated the wheel was spinning quickly.",
   logic=["extending beyond the rim ↔ extending beyond the wheel's perimeter。",
          "had its brakes on ↔ 选项 E use of brakes。",
          "原词几乎复现，属送分题，前提是看懂图。"],
   ans="E", ansnote=["use of brakes", "perimeter ＝ rim"],
   stitle="P3 Q30｜Subjects assumed that ... and that ... 双宾语从句",
   sent="Subjects assumed that spokes extending beyond the wheel's perimeter signified that the wheel had "
        "its brakes on and that dashed spokes indicated the wheel was spinning quickly.",
   core="Subjects assumed that extending spokes signified braking and dashed spokes indicated fast spinning.",
   layers=["assumed 后接两个并列的 that 从句（and that ... 是第二个）。",
           "第一个从句里还套了一个 that：signified that ...。",
           "extending beyond ... 是现在分词后置定语，修饰 spokes。",
           "两个从句分别对应 Q30 和 Q31。"],
   cn="受试者认为，伸出轮圈之外的轮辐表示轮子正在刹车，而虚线轮辐则表示轮子在快速旋转。",
   vocab=["perimeter 周边、轮圈 ↔ rim / edge；signify 表示 ↔ indicate / mean",
          "have the brakes on 刹车中"]),
 # ------------------------------------------------------------------ Q31
 dict(n=31, kind="MATCH",
   title="P3 Q31｜虚线轮辐＝什么运动",
   stem="Diagram 31：轮辐为虚线／断续线（dashed spokes）",
   entry=["本图特征：线是断开的。", "在同一句里找 dashed。"],
   ev="P4 S3: ... and that dashed spokes indicated the wheel was spinning quickly.",
   logic=["dashed spokes 原词复现。",
          "spinning quickly ↔ 选项 C rapid spinning。",
          "注意与 A steady spinning 区分：quickly≠steadily。"],
   ans="C", ansnote=["rapid spinning", "quickly ＝ rapid"],
   stitle="P3 Q31｜五种画法与五种运动的完整对照",
   sent="Most guessed that the curved spokes indicated ... spinning steadily; the wavy spokes ... wobbling; "
        "and the bent spokes ... jerking. Subjects assumed that spokes extending beyond the perimeter "
        "signified brakes and that dashed spokes indicated ... spinning quickly.",
   core="curved→steady；wavy→wobbling；bent→jerky；extending→brakes；dashed→rapid.",
   layers=["原文用分号把三组并列在一句里。",
           "第二句再补两组，一共五组。",
           "配对题先把五组全画成表，再回头看图。",
           "题目只考三个图，另两组是干扰项来源。"],
   cn="多数人猜测：弯曲轮辐＝平稳旋转；波浪轮辐＝摇晃；折线轮辐＝顿挫；伸出轮圈＝刹车；虚线轮辐＝快速旋转。",
   vocab=["dashed 虚线的；wavy 波浪形的；bent 弯折的",
          "wobble 摇晃；jerk 顿挫、急动"]),
 # ------------------------------------------------------------------ Q32
 dict(n=32, kind="MATCH",
   title="P3 Q32｜弧形轮辐＝什么运动",
   stem="Diagram 32：轮辐为弯曲的弧线（curved spokes）",
   entry=["本图特征：线是弯的。", "回到 P4 S2 找 curved。"],
   ev="P4 S2: Most guessed that the curved spokes indicated that the wheel was spinning steadily; the wavy "
      "spokes, they thought, suggested that the wheel was wobbling; and the bent spokes were taken as a sign "
      "that the wheel was jerking.",
   logic=["curved spokes 原词复现。",
          "spinning steadily ↔ 选项 A steady spinning。",
          "别被 D wobbling 干扰：那是 wavy（波浪）不是 curved（弧形）。"],
   ans="A", ansnote=["steady spinning", "curved ≠ wavy"],
   stitle="P3 Q32｜分号并列三组 + 插入语 they thought",
   sent="Most guessed that the curved spokes indicated that the wheel was spinning steadily; the wavy spokes, "
        "they thought, suggested that the wheel was wobbling; and the bent spokes were taken as a sign that "
        "the wheel was jerking.",
   core="Curved spokes indicated steady spinning; wavy spokes suggested wobbling; bent spokes meant jerking.",
   layers=["分号把三组“画法→运动”并列起来，结构完全对称。",
           "they thought 是插入语，去掉不影响主干。",
           "were taken as a sign that ... 是被动的“被视为……的标志”。",
           "对称结构一旦看出，三组关系一次读完。"],
   cn="多数人猜测：弯曲的轮辐表示轮子在平稳旋转；他们认为波浪形轮辐表示轮子在摇晃；折线轮辐则被视为轮子在顿挫的标志。",
   vocab=["steadily 平稳地 ↔ evenly；be taken as 被视为 ↔ be regarded as",
          "curved 弧形的（≠ wavy 波浪形）"]),
 # ------------------------------------------------------------------ Q33
 dict(n=33, kind="SUMMARY",
   title="P3 Q33｜a set of word ____ was used",
   stem="... a set of word 33 …… was used to investigate whether blind and sighted people ...",
   entry=["word + 空格 → 名词，作复合名词后半。", "词库里可选：pairs / words / associations。"],
   ev="P7 S1: We gave a list of twenty pairs of words to sighted subjects and asked them to pick from each "
      "pair the term that best related to a circle ...",
   logic=["原文是 twenty pairs of words＝二十组词对。",
          "word pairs 正是“词对”的复合说法。",
          "选 associations 会与后文“联想”混淆，不合语法搭配。"],
   ans="pairs", ansnote=["word pairs 词对。", "词库原词，勿改形。"],
   stitle="P3 Q33｜a list of twenty pairs of words 的层级",
   sent="We gave a list of twenty pairs of words to sighted subjects and asked them to pick from each pair "
        "the term that best related to a circle and the term that best related to a square.",
   core="We gave a list of word pairs to sighted subjects and asked them to pick the term.",
   layers=["a list of twenty pairs of words 是三层 of 结构：清单→词对→词。",
           "gave ... and asked ... 是并列谓语。",
           "pick from each pair the term ... 是宾语后置（term 被定语从句拉长）。",
           "两个 that 从句结构对称，分别指圆和方。"],
   cn="我们给明眼受试者一份包含二十组词对的清单，让他们从每一对中挑出最贴合圆形的词和最贴合方形的词。",
   vocab=["pair 一对 ↔ two-word set；term 词语 ↔ word",
          "relate to 与……相关 ↔ go with / fit"]),
 # ------------------------------------------------------------------ Q34
 dict(n=34, kind="SUMMARY",
   title="P3 Q34｜the symbolism in abstract ____",
   stem="... perceived the symbolism in abstract 34 …… in the same way.",
   entry=["abstract + 空格 → 可被“抽象”修饰的名词。", "词库里可选：shapes。"],
   ev="P6 S3: ... I have begun exploring how well blind people understand the symbolism behind shapes such "
      "as hearts that do not directly represent their meaning.",
   logic=["symbolism 原词复现，后面接的是 shapes。",
          "整个实验就是圆形与方形＝抽象形状。",
          "填 shapes，复数与 abstract 搭配自然。"],
   ans="shapes", ansnote=["复数 shapes。", "圆与方＝抽象形状。"],
   stitle="P3 Q34｜such as + that 定语从句",
   sent="With Chang Hong Liu, a doctoral student from China, I have begun exploring how well blind people "
        "understand the symbolism behind shapes such as hearts that do not directly represent their meaning.",
   core="I have begun exploring how well blind people understand the symbolism behind shapes.",
   layers=["With ... China 是伴随状语＋同位语，先盖住。",
           "exploring 后接 how well ... 名词性从句。",
           "such as hearts 是举例，that 从句修饰 shapes/hearts。",
           "do not directly represent their meaning ＝ “抽象”的定义。"],
   cn="我与来自中国的博士生刘长虹一起，开始研究盲人在多大程度上理解心形这类并不直接表示其含义的形状背后的象征意义。",
   vocab=["symbolism 象征意义；abstract 抽象的 ↔ not literal",
          "represent 表示 ↔ stand for"]),
 # ------------------------------------------------------------------ Q35
 dict(n=35, kind="SUMMARY",
   title="P3 Q35｜From the ____ volunteers, everyone thought ...",
   stem="From the 35 …… volunteers, everyone thought a circle fitted 'soft' while a square fitted 'hard'.",
   entry=["空格修饰 volunteers → 人群类别。", "词库里可选：blind / sighted。"],
   ev="P7 S1: We gave a list of twenty pairs of words to sighted subjects ... "
      "P8 S1: All our subjects deemed the circle soft and the square hard.",
   logic=["第一轮实验的对象是 sighted subjects（明眼人）。",
          "All our subjects ＝ 全体明眼受试者都选了 soft/hard。",
          "盲人是后来才测的（见 P8 S5），所以此处是 sighted。"],
   ans="sighted", ansnote=["第一轮＝明眼人。", "与 38 blind 对照。"],
   stitle="P3 Q35｜All our subjects 的指代范围",
   sent="We gave a list of twenty pairs of words to sighted subjects ... All our subjects deemed the circle "
        "soft and the square hard.",
   core="All our (sighted) subjects deemed the circle soft and the square hard.",
   layers=["our subjects 回指上一段的 sighted subjects。",
           "deem A B 是“认为 A 是 B”的双宾结构。",
           "摘要题的人群词必须靠上下文回指确定。",
           "100% 的共识对应 everyone thought。"],
   cn="我们把二十组词对给了明眼受试者……我们所有的受试者都认为圆形是柔软的，方形是坚硬的。",
   vocab=["deem 认为 ↔ consider / regard；sighted 有视力的",
          "volunteer 志愿者 ↔ subject 受试者"]),
 # ------------------------------------------------------------------ Q36
 dict(n=36, kind="SUMMARY",
   title="P3 Q36｜only 51% of the ____ volunteers",
   stem="However, only 51% of the 36 …… volunteers assigned a circle to 37 …….",
   entry=["空格仍修饰 volunteers。", "看 51% 这个数字属于哪一组人。"],
   ev="P8 S4: And only 51% linked deep to circle and shallow to square. (See Fig. 2.)",
   logic=["Fig. 2 的百分比是 consensus among sighted subjects。",
          "51% 属于明眼人这一组的统计结果。",
          "盲人只有四人，不会用百分比表达。"],
   ans="sighted", ansnote=["与 35 同词，可重复。", "NB 允许重复使用。"],
   stitle="P3 Q36｜百分比归属靠图注锁定",
   sent="And only 51% linked deep to circle and shallow to square. (See Fig. 2.) — Fig. 2: These percentages "
        "show the level of consensus among sighted subjects.",
   core="Only 51% of sighted subjects linked deep to circle.",
   layers=["主句省略了主语范围，靠图注补全。",
           "linked A to B 是“把 A 与 B 联系起来”。",
           "and 后半句是对称结构：shallow to square。",
           "图注是本题唯一的归属证据，不能跳过。"],
   cn="而只有51%的人把 deep 与圆形、shallow 与方形联系起来。（见图2；图注说明这些百分比是明眼受试者的共识度。）",
   vocab=["link A to B 把A与B联系 ↔ assign / match",
          "consensus 共识；percentage 百分比"]),
 # ------------------------------------------------------------------ Q37
 dict(n=37, kind="SUMMARY",
   title="P3 Q37｜assigned a circle to ____",
   stem="... only 51% of the sighted volunteers assigned a circle to 37 …….",
   entry=["assigned a circle to + 空格 → 形容词。", "词库里可选：deep / shallow / soft / hard。"],
   ev="P8 S4: And only 51% linked deep to circle and shallow to square.",
   logic=["assigned a circle to ↔ linked ... to circle。",
          "与 circle 配对的是 deep，与 square 配对的是 shallow。",
          "方向不能反：填 shallow 就错了。"],
   ans="deep", ansnote=["圆↔deep。", "方↔shallow。"],
   stitle="P3 Q37｜A to B 与 B to A 的方向陷阱",
   sent="And only 51% linked deep to circle and shallow to square.",
   core="51% linked deep to circle.",
   layers=["原文语序是 linked [deep] to [circle]。",
           "摘要语序是 assigned [a circle] to [___]。",
           "两句的介词方向被调换了，必须重新对位。",
           "画箭头 deep → circle，再填空最稳。"],
   cn="而只有51%的人把“深”与圆形、“浅”与方形联系起来。",
   vocab=["deep 深的（↔ shallow 浅的）",
          "assign A to B ＝ link A to B（注意 A、B 的位置会被改写）"]),
 # ------------------------------------------------------------------ Q38
 dict(n=38, kind="SUMMARY",
   title="P3 Q38｜test repeated with ____ volunteers",
   stem="When the test was later repeated with 38 …… volunteers, ...",
   entry=["later repeated → 第二轮实验对象。", "与 35/36 的人群相对。"],
   ev="P8 S5: When we tested four totally blind volunteers using the same list, we found that their choices "
      "closely resembled those made by the sighted subjects.",
   logic=["later / repeated ↔ tested ... using the same list。",
          "第二轮的对象是 four totally blind volunteers。",
          "volunteers 原词复现，直接填 blind。"],
   ans="blind", ansnote=["第二轮＝盲人。", "四位全盲志愿者。"],
   stitle="P3 Q38｜When ... , we found that ... 的双层结构",
   sent="When we tested four totally blind volunteers using the same list, we found that their choices "
        "closely resembled those made by the sighted subjects.",
   core="We found that their choices closely resembled those of the sighted subjects.",
   layers=["When 从句交代实验条件（对象＋工具）。",
           "using the same list 是分词状语，保证可比性。",
           "主句 we found that ... 才是结论。",
           "those = the choices，made by ... 是过去分词后置定语。"],
   cn="当我们用同一份清单测试四位全盲志愿者时，我们发现他们的选择与明眼受试者的选择非常相似。",
   vocab=["totally blind 全盲的；resemble 相似 ↔ be similar to",
          "repeat the test 重做实验"]),
 # ------------------------------------------------------------------ Q39
 dict(n=39, kind="SUMMARY",
   title="P3 Q39｜they made ____ choices",
   stem="... it was found that they made 39 …… choices.",
   entry=["空格修饰 choices → 形容词。", "词库里可选：identical / similar。"],
   ev="P8 S5: ... we found that their choices closely resembled those made by the sighted subjects. "
      "P8 S7: He made only one match differing from the consensus ...",
   logic=["closely resembled ＝ 非常相似，但不是完全相同。",
          "P8 S7 明确说有一处不同 → identical（完全相同）过强。",
          "选 similar，程度刚好。"],
   ans="similar", ansnote=["不能选 identical。", "有一处不一致。"],
   stitle="P3 Q39｜resembled ≠ identical 的程度差",
   sent="... their choices closely resembled those made by the sighted subjects. ... He made only one match "
        "differing from the consensus, assigning 'far' to square and 'near' to circle.",
   core="Their choices resembled those of the sighted, with one match differing.",
   layers=["closely resembled 是“很像”，仍留有差异空间。",
           "only one match differing 是具体的反证。",
           "differing from ... 是现在分词后置定语。",
           "词库题最后一步永远是核对“程度是否被放大”。"],
   cn="他们的选择与明眼受试者非常相似……那位受试者只有一处与共识不同，他把“远”配给方形、“近”配给圆形。",
   vocab=["resemble 相似 ↔ be similar to（≠ identical 完全相同）",
          "differ from 不同于；consensus 共识"]),
 # ------------------------------------------------------------------ Q40
 dict(n=40, kind="MCQ",
   title="P3 Q40｜全文结论是什么",
   stem="Which of the following statements best summarises the writer's general conclusion?",
   options=["The blind represent some aspects of reality differently from sighted people.",
            "The blind comprehend visual metaphors in similar ways to sighted people.",
            "The blind may create unusual and effective symbols to represent reality.",
            "The blind may be successful artists if given the right training."],
   entry=["主旨题：找作者自己写的结论句。", "锚点：Thus, we concluded that ...。"],
   ev="P8 S9: Thus, we concluded that the blind interpret abstract shapes as sighted people do. "
      "（P6 S1: the blind understand other kinds of visual metaphors as well）",
   logic=["interpret ... as sighted people do ＝ 与明眼人理解方式相同 → B。",
          "A 说“不同”，与结论相反。",
          "C、D 是文中细节或未提内容，不是全文结论。"],
   ans="B", ansnote=["similar ways", "全文结论句 Thus ..."],
   stitle="P3 Q40｜Thus 引出的总结句",
   sent="Thus, we concluded that the blind interpret abstract shapes as sighted people do.",
   core="The blind interpret abstract shapes as sighted people do.",
   layers=["Thus 是明确的结论信号词，主旨题优先找它。",
           "concluded that ... 后面就是作者的立场。",
           "as sighted people do 是方式状语从句，do 代替 interpret。",
           "主旨题不要选“只覆盖一段”的选项。"],
   cn="因此我们得出结论：盲人解读抽象形状的方式与明眼人相同。",
   vocab=["interpret 解读 ↔ comprehend / understand；conclude 得出结论",
          "visual metaphor 视觉隐喻；as ... do 与……一样"]),
]
