# -*- coding: utf-8 -*-
"""第二节课作业 · The Development of Plastics —— 逐题讲解内容（表格填空 + 判断）。"""

MAP = [
    ("P1–P3", ["塑料＝橡胶替代品", "celluloid 第一种塑料", "Bakelite 第一种热固性"]),
    ("P4–P7", ["polythene / PVC / Teflon", "polystyrene / polyurethane", "nylon 与合成纤维"]),
    ("P8–P9", ["优点即缺点：不可毁", "回收困难", "可降解与储存条件"]),
]

STRATEGY = [
    ("Q1–7 表格填空：表格按“材料”逐行推进，先看列标题（Properties / Common uses）定词性。",),
    ("表格顺序≠原文顺序的绝对保证，但本篇基本同步：Celluloid→Bakelite→Polythene→PVC→…",),
    ("Q8–13 判断题：本篇陷阱是化学关系（same / different）与程度词（more durable）。",),
]

SUMMARY = [
    ("表格定位", ["按材料名找段", "按列定词性", "≤3 词"]),
    ("判断三陷阱", ["same vs different", "职业身份未提", "more durable 反向"]),
    ("作业收获", ["错在定位还是替换", "写下错因", "带着问题进新课"]),
]

Q = [
 # ------------------------------------------------------------------ Q1
 dict(n=1, kind="TABLE",
   title="作业 Q1｜Celluloid 行：还有什么著名用途",
   stem="Celluloid｜1860s｜USA｜…｜Common uses：billiard balls / cutlery / clothing / 1 ………………",
   entry=["空格在 Common uses 列 → 填“用途/产品”名词。", "锚点：celluloid 的著名产品。"],
   ev="P2 S6: But perhaps the best-known celluloid product was photographic film, without which the film "
      "industry could never have taken off at the end of the 19th century.",
   logic=["表格前三项 billiard balls / cutlery / clothing 对应 P2 S2、S5。",
          "S6 用 best-known celluloid product 引出最后一项。",
          "取系动词后的名词短语：photographic film。"],
   ans="photographic film", ansnote=["两词，≤3。", "不要只写 film。"],
   stitle="作业 Q1｜without which 引导的非限定定语从句",
   sent="But perhaps the best-known celluloid product was photographic film, without which the film "
        "industry could never have taken off at the end of the 19th century.",
   core="The best-known celluloid product was photographic film.",
   layers=["主干是 S + be + 表语：product was photographic film。",
           "perhaps 是程度副词，不影响事实。",
           "without which = 介词 + 关系代词，which 指 photographic film。",
           "could never have taken off 是虚拟语气：没有它就不可能兴起。"],
   cn="但也许最著名的赛璐珞产品是照相胶片；没有它，电影业在19世纪末根本不可能起步。",
   vocab=["take off 起飞、兴起 ↔ become successful；best-known 最著名的",
          "application = use（用途），表格常用 Common uses"]),
 # ------------------------------------------------------------------ Q2
 dict(n=2, kind="TABLE",
   title="作业 Q2｜1907 年美国诞生的是哪种塑料",
   stem="2 ………………｜1907｜USA｜can't be softened after setting; good insulator; resistant to water and acid",
   entry=["空格在 Name 列 → 填材料名。", "锚点：1907 + 不能再软化。"],
   ev="P3 S2–S3: In 1907, Leo Baekeland ..., a Belgian chemist working in the USA, invented a different "
      "kind of plastic ... Baekeland called it Bakelite, and it was the first of the thermosets—plastics "
      "that can be cast and moulded while hot, but cannot be softened by heat and reshaped once they have set.",
   logic=["1907 与 USA 原词复现，一句锁定。",
          "can't be softened after setting ↔ cannot be softened ... once they have set。",
          "材料名在 called it 之后：Bakelite（首字母大写照抄）。"],
   ans="Bakelite", ansnote=["一词，首字母大写。", "不要填 Baekeland（人名）。"],
   stitle="作业 Q2｜thermosets 的破折号定义",
   sent="Baekeland called it Bakelite, and it was the first of the thermosets—plastics that can be cast and "
        "moulded while hot, but cannot be softened by heat and reshaped once they have set.",
   core="It was the first of the thermosets.",
   layers=["called it Bakelite 是“把它叫作……”，宾补结构。",
           "破折号后是 thermosets 的定义，整段可先跳过。",
           "定义里 can ... but cannot ... 是本题与 Q10 的关键对比。",
           "once they have set 是时间状语从句：一旦定型。"],
   cn="Baekeland 把它称作 Bakelite；它是第一种热固性塑料——这类塑料可在受热时浇铸成型，但一旦定型就无法再受热软化和重塑。",
   vocab=["cast 浇铸；mould 塑形 ↔ shape；set 凝固、定型",
          "thermoset 热固性塑料（↔ thermoplastic 热塑性塑料）"]),
 # ------------------------------------------------------------------ Q3
 dict(n=3, kind="TABLE",
   title="作业 Q3｜Bakelite 行：另一项常见用途",
   stem="2 Bakelite｜…｜Common uses：3 ……………… / household object",
   entry=["空格在 Common uses 列 → 填产品名。", "锚点：Bakelite 的性质带出用途。"],
   ev="P3 S4–S5: Bakelite was a good insulator, and was resistant to water and acid. With these properties "
      "it was soon being used in the manufacture of electrical switches as well as a variety of domestic items.",
   logic=["表格 Properties 列正是 S4，用途在紧接的 S5。",
          "household object ↔ domestic items（家用物品）。",
          "as well as 前面的那一项就是答案：electrical switches。"],
   ans="electrical switches", ansnote=["两词，保留复数。", "别写 switches 一词。"],
   stitle="作业 Q3｜With these properties 的回指",
   sent="Bakelite was a good insulator, and was resistant to water and acid. With these properties it was "
        "soon being used in the manufacture of electrical switches as well as a variety of domestic items.",
   core="It was soon being used in the manufacture of electrical switches.",
   layers=["these properties 回指上一句的两条性质，必须连读两句。",
           "was being used 是过去进行时的被动。",
           "in the manufacture of ... 是“用于制造……”。",
           "as well as 连接两类用途，前者是编号空的答案。"],
   cn="Bakelite 是良好的绝缘体，且耐水耐酸。凭借这些性质，它很快被用于制造电气开关以及各种家用物品。",
   vocab=["insulator 绝缘体 ↔ insulation；resistant to 耐……的",
          "domestic items = household objects（家用物品）"]),
 # ------------------------------------------------------------------ Q4
 dict(n=4, kind="TABLE",
   title="作业 Q4｜Polythene 出自哪个国家",
   stem="Polythene｜1930s｜4 ………………｜can be softened and reshaped by heat",
   entry=["空格在 Country of origin 列 → 填国名。", "锚点：1930s + polythene。"],
   ev="P4 S3: In the 1930s, chemists in Britain discovered that the gas ethylene would polymerize under "
      "heat and pressure to form a thermoplastic they called polythene.",
   logic=["1930s 与 polythene 双锚点，一句命中。",
          "Country of origin ↔ chemists in Britain（在英国的化学家）。",
          "填国名 Britain，不要写 British 或 England。"],
   ans="Britain", ansnote=["一词，国名。", "非 British / England。"],
   stitle="作业 Q4｜discovered that ... 宾语从句 + 省略关系词",
   sent="In the 1930s, chemists in Britain discovered that the gas ethylene would polymerize under heat and "
        "pressure to form a thermoplastic they called polythene.",
   core="Chemists in Britain discovered that ethylene would polymerize to form a thermoplastic.",
   layers=["主干 chemists discovered that ...，主语带 in Britain 后置定语。",
           "that 从句里主语是 the gas ethylene。",
           "under heat and pressure 是条件状语。",
           "a thermoplastic (which) they called polythene —— 关系代词被省略。"],
   cn="20世纪30年代，英国的化学家发现乙烯气体在加热加压下会聚合，形成一种被他们称为聚乙烯的热塑性塑料。",
   vocab=["polymerize 聚合；thermoplastic 热塑性塑料",
          "country of origin 原产国 ↔ chemists in + 国名"]),
 # ------------------------------------------------------------------ Q5
 dict(n=5, kind="TABLE",
   title="作业 Q5｜Rigid PVC 的性质是什么",
   stem="Rigid PVC｜…｜Properties：is 5 ………………｜Common uses：external piping",
   entry=["is + 空格 → 形容词。", "锚点：rigid PVC + 户外管道。"],
   ev="P4 S6: A small change in the starting material—replacing a hydrogen atom in ethylene with a chlorine "
      "atom—produced rigid PVC (polyvinyl chloride), a fireproof plastic suitable for drains and gutters.",
   logic=["external piping ↔ drains and gutters（排水管与檐槽）。",
          "rigid PVC 后的同位语 a fireproof plastic 给出性质。",
          "is + 形容词，所以填 fireproof，不能填 fireproof plastic。"],
   ans="fireproof", ansnote=["一词，形容词。", "由 is 决定词性。"],
   stitle="作业 Q5｜破折号插入语 + 同位语给性质",
   sent="A small change in the starting material—replacing a hydrogen atom in ethylene with a chlorine "
        "atom—produced rigid PVC (polyvinyl chloride), a fireproof plastic suitable for drains and gutters.",
   core="A small change produced rigid PVC.",
   layers=["主语 A small change，谓语 produced，宾语 rigid PVC。",
           "两个破折号之间解释“改了什么”，先整块盖住。",
           "a fireproof plastic ... 是 rigid PVC 的同位语。",
           "suitable for ... 是形容词短语后置定语。"],
   cn="起始材料上的一个小改动——把乙烯中的一个氢原子换成氯原子——制造出了硬质 PVC，这是一种适用于排水管和檐槽的防火塑料。",
   vocab=["fireproof 防火的 ↔ fire-resistant；rigid 硬质的 ↔ stiff",
          "drains and gutters 排水管与檐槽 ＝ external piping"]),
 # ------------------------------------------------------------------ Q6
 dict(n=6, kind="TABLE",
   title="作业 Q6｜Polystyrene 像什么",
   stem="Polystyrene｜1930s｜Germany｜Properties：resembles 6 ………………",
   entry=["resembles + 空格 → 名词。", "锚点：polystyrene。"],
   ev="P5 S1: Polystyrene, a hard, clear material like glass, was developed during the 1930s in Germany, "
      "and its applications included food containers and toys.",
   logic=["resembles ↔ like（像……）。",
          "a hard, clear material like glass 是 polystyrene 的同位语。",
          "取 like 后的名词：glass。"],
   ans="glass", ansnote=["一词。", "resembles = like。"],
   stitle="作业 Q6｜主语后紧跟同位语，主干被拉开",
   sent="Polystyrene, a hard, clear material like glass, was developed during the 1930s in Germany, and its "
        "applications included food containers and toys.",
   core="Polystyrene was developed during the 1930s in Germany.",
   layers=["主语 Polystyrene 之后立刻插入同位语，先用逗号定位边界。",
           "盖掉同位语，主干 was developed ... 立刻显形。",
           "and 后并列第二个分句，讲用途。",
           "本题答案恰恰藏在被“盖掉”的同位语里——盖是为了看清结构，不是不读。"],
   cn="聚苯乙烯是一种像玻璃一样坚硬透明的材料，于20世纪30年代在德国研制出来，其用途包括食品容器和玩具。",
   vocab=["resemble 类似于 ↔ be like / look like；clear 透明的",
          "applications 用途 ↔ uses"]),
 # ------------------------------------------------------------------ Q7
 dict(n=7, kind="TABLE",
   title="作业 Q7｜Polyurethane 通常做成什么形态",
   stem="Polyurethane｜…｜Germany｜usually manufactured as a 7 ………………｜insulation",
   entry=["as a + 空格 → 单数可数名词。", "锚点：polyurethane + 保温材料。"],
   ev="P5 S3: Polyurethane, developed in the same country, was commonly produced as a foam, which was very "
      "useful in the production of insulating materials.",
   logic=["usually ↔ commonly；manufactured ↔ produced。",
          "as a + 名词 与原文 as a foam 完全对位。",
          "Germany 由 the same country 回指上一句得来。"],
   ans="foam", ansnote=["一词，单数。", "a 提示单数可数。"],
   stitle="作业 Q7｜过去分词短语作后置定语 + which 从句",
   sent="Polyurethane, developed in the same country, was commonly produced as a foam, which was very "
        "useful in the production of insulating materials.",
   core="Polyurethane was commonly produced as a foam.",
   layers=["developed in the same country 是过去分词后置定语，先盖住。",
           "the same country 回指上一句的 Germany——表格该列答案由此而来。",
           "主干 was produced as a foam。",
           "which 指代 foam，补充说明用途。"],
   cn="聚氨酯也是在同一个国家研制的，通常被制成泡沫，这种形态在生产保温材料方面非常有用。",
   vocab=["foam 泡沫；insulating materials 保温/绝缘材料",
          "commonly = usually；produced = manufactured"]),
 # ------------------------------------------------------------------ Q8
 dict(n=8, kind="TFNG",
   title="作业 Q8｜very different：化学关系被写反",
   stem="The chemical structure of rubber is very different from that of plastics.",
   entry=["锚点：chemical structure + different。", "先问：原文说“同”还是“异”？"],
   ev="P1 S2–S3: Chemically, rubber is a polymer—a compound containing large molecules ... The same bonding "
      "principle—polymerization—is the basis of the creation of a huge range of plastics.",
   logic=["原文说橡胶是聚合物，塑料靠同一种成键原理生成。",
          "The same bonding principle 明确指出两者“相同”。",
          "题干说 very different，与原文正相反。"],
   ans="FALSE", ansnote=["same 与 different 对撞。", "有明确矛盾句。"],
   stitle="作业 Q8｜两个破折号定义 + The same 的回指",
   sent="Chemically, rubber is a polymer—a compound containing large molecules that are formed by the "
        "bonding of many smaller, simpler units, repeated over and over again. The same bonding principle—"
        "polymerization—is the basis of the creation of a huge range of plastics.",
   core="Rubber is a polymer. The same bonding principle is the basis of plastics.",
   layers=["第一句破折号后是 polymer 的定义，containing / formed 都是后置修饰。",
           "第二句主语是 The same bonding principle——The same 是判断依据。",
           "polymerization 夹在破折号中间，是同位解释。",
           "两句连读才能看出“橡胶与塑料同源”。"],
   cn="从化学角度看，橡胶是一种聚合物——即由许多更小更简单的单元反复成键而形成大分子的化合物。同样的成键原理（聚合）也是化工业创造出大量塑料的基础。",
   vocab=["polymer 聚合物；compound 化合物；bonding 成键",
          "the same ... as ＝ 相同（判断题常考的关系词）"]),
 # ------------------------------------------------------------------ Q9
 dict(n=9, kind="TFNG",
   title="作业 Q9｜industrial chemist：职业身份未提",
   stem="John Wesley Hyatt was an industrial chemist.",
   entry=["锚点：John Wesley Hyatt + 职业。", "问的是“他是不是工业化学家”。"],
   ev="P2 S3: The prize was won by John Wesley Hyatt, with a material called celluloid.（全文只提到他赢得奖金）",
   logic=["原文只说他用赛璐珞赢得了奖金。",
          "对他的职业、身份、受训背景只字未提。",
          "对比 P3 S2 明确写了 Baekeland 是 a Belgian chemist——可见作者要提就会提。"],
   ans="NOT GIVEN", ansnote=["人名在，职业不在。", "缺信息，不是矛盾。"],
   stitle="作业 Q9｜被动语态与 with 表方式",
   sent="In the 1860s, $10,000 was offered to anybody who could replace ivory—supplies of which were "
        "declining—with something equally good ... The prize was won by John Wesley Hyatt, with a material "
        "called celluloid.",
   core="The prize was won by John Wesley Hyatt.",
   layers=["was offered to anybody who ... 是被动 + 定语从句。",
           "supplies of which were declining 是插入的非限定定从：象牙供应在减少。",
           "The prize was won by X 的 by 后是获奖者。",
           "with a material called celluloid 表方式，不是身份。"],
   cn="19世纪60年代，有人悬赏一万美元，奖给能用同样好的材料替代象牙（其供应正在减少）制造台球的人。这笔奖金被 John Wesley Hyatt 用一种叫赛璐珞的材料赢得。",
   vocab=["decline 减少 ↔ fall / go down；ivory 象牙",
          "equally good 同样好的；win the prize 赢得奖金"]),
 # ------------------------------------------------------------------ Q10
 dict(n=10, kind="TFNG",
   title="作业 Q10｜react to heat：两者恰恰相反",
   stem="Celluloid and Bakelite react in the same way to heat.",
   entry=["锚点：celluloid / Bakelite / heat。", "需要同时看两段各一句。"],
   ev="P3 S1: Celluloid can be repeatedly softened and reshaped by heat, and is known as a thermoplastic. "
      "P3 S3: ... the first of the thermosets—plastics that ... cannot be softened by heat and reshaped once "
      "they have set.",
   logic=["Celluloid ＝ thermoplastic：可反复受热软化。",
          "Bakelite ＝ thermoset：定型后不能再受热软化。",
          "两者对热的反应正好相反，题干说 same way → 矛盾。"],
   ans="FALSE", ansnote=["热塑 vs 热固。", "同段两句对撞。"],
   stitle="作业 Q10｜thermoplastic 与 thermoset 的对照",
   sent="Celluloid can be repeatedly softened and reshaped by heat, and is known as a thermoplastic. ... the "
        "first of the thermosets—plastics that can be cast and moulded while hot, but cannot be softened by "
        "heat and reshaped once they have set.",
   core="Celluloid can be softened by heat; thermosets cannot be softened by heat.",
   layers=["两句的关键谓语都是 be softened by heat，一个 can，一个 cannot。",
           "判断题遇到 same / different，先把两边的谓语并排写出来。",
           "repeatedly 与 once they have set 是两种时间条件。",
           "-plastic 与 -set 两个词根本身就提示了差别。"],
   cn="赛璐珞可以被反复加热软化并重塑，被称为热塑性塑料；而热固性塑料受热时可浇铸成型，但一旦定型就不能再受热软化重塑。",
   vocab=["thermoplastic 热塑性 ↔ can be softened repeatedly",
          "thermoset 热固性 ↔ cannot be softened once set"]),
 # ------------------------------------------------------------------ Q11
 dict(n=11, kind="TFNG",
   title="作业 Q11｜several plastics：混合材料难回收",
   stem="If an object is made of several plastics, these prove hard to break down and reuse.",
   entry=["锚点：several plastics + reuse。", "找“回收难不难”的句子。"],
   ev="P8 S4: Nor is it very easy to recycle plastics, as different types of plastic are often found in the "
      "same items and call for different treatments.",
   logic=["break down and reuse ↔ recycle（回收再利用）。",
          "several plastics in one object ↔ different types ... in the same items。",
          "Nor is it very easy ＝ 也不容易 → 与题干 hard 一致。"],
   ans="TRUE", ansnote=["Nor ＝ 也不。", "否定倒装别读反。"],
   stitle="作业 Q11｜Nor 引起的部分倒装",
   sent="Nor is it very easy to recycle plastics, as different types of plastic are often found in the same "
        "items and call for different treatments.",
   core="It is not very easy to recycle plastics.",
   layers=["Nor 置于句首，助动词提到主语前：Nor is it ...（部分倒装）。",
           "还原语序：It is not very easy to recycle plastics either。",
           "it 是形式主语，真正主语是 to recycle plastics。",
           "as 引导原因状语从句，给出“为什么难”。"],
   cn="塑料也不太容易回收，因为同一件物品中往往含有不同种类的塑料，而它们需要不同的处理方式。",
   vocab=["recycle 回收 ↔ break down and reuse；call for 需要 ↔ require",
          "Nor + 倒装 ＝ 也不（否定延续）"]),
 # ------------------------------------------------------------------ Q12
 dict(n=12, kind="TFNG",
   title="作业 Q12｜more durable：淀粉的作用被写反",
   stem="Adding starch to plastic makes it more durable.",
   entry=["锚点：starch + durable。", "先问：加淀粉是为了更耐用还是更易坏？"],
   ev="P9 S1: Plastics can be made biodegradable by incorporating into their structure a material such as "
      "starch, which is attacked by bacteria and causes the plastic to fall apart.",
   logic=["加淀粉是为了 biodegradable（可生物降解）。",
          "which ... causes the plastic to fall apart ＝ 让塑料散架。",
          "题干说 more durable（更耐用），方向完全相反。"],
   ans="FALSE", ansnote=["fall apart ≠ durable。", "作用被写反。"],
   stitle="作业 Q12｜by + 动名词表方式 + which 从句",
   sent="Plastics can be made biodegradable by incorporating into their structure a material such as starch, "
        "which is attacked by bacteria and causes the plastic to fall apart.",
   core="Plastics can be made biodegradable by incorporating starch.",
   layers=["主干是 Plastics can be made biodegradable（被动 + 宾补）。",
           "by incorporating ... 是方式状语。",
           "incorporating into their structure a material —— 宾语后置，先还原成 incorporating a material into their structure。",
           "which 指 starch，带出两个并列谓语 is attacked / causes。"],
   cn="通过在结构中加入淀粉之类的材料，可以使塑料变得可生物降解；这种材料会被细菌侵蚀，并使塑料散架。",
   vocab=["biodegradable 可生物降解的；incorporate 加入 ↔ add / include",
          "fall apart 散架、解体（↔ durable 耐用的）"]),
 # ------------------------------------------------------------------ Q13
 dict(n=13, kind="TFNG",
   title="作业 Q13｜storage conditions：必须避光保存",
   stem="Containers which are designed to decompose need particular storage conditions.",
   entry=["锚点：decompose + storage。", "找“怎么存放”的句子。"],
   ev="P9 S2: Other materials can be incorporated that gradually decay in sunlight—although bottles made of "
      "such materials have to be stored in the dark, to ensure they do not disintegrate before they have "
      "been used.",
   logic=["designed to decompose ↔ gradually decay in sunlight。",
          "containers ↔ bottles（瓶子是容器的一种）。",
          "particular storage conditions ↔ have to be stored in the dark（必须避光）。"],
   ans="TRUE", ansnote=["in the dark ＝ 特定条件。", "三处替换齐全。"],
   stitle="作业 Q13｜although 让步 + to ensure 目的状语",
   sent="Other materials can be incorporated that gradually decay in sunlight—although bottles made of such "
        "materials have to be stored in the dark, to ensure they do not disintegrate before they have been used.",
   core="Bottles made of such materials have to be stored in the dark.",
   layers=["that gradually decay in sunlight 是修饰 materials 的定语从句（与主语分离）。",
           "破折号后的 although 从句才是本题的答案句。",
           "made of such materials 是过去分词后置定语。",
           "to ensure ... 是目的状语，说明为什么要避光。"],
   cn="也可以加入另一些在阳光下会逐渐分解的材料——不过用这类材料制成的瓶子必须避光保存，以确保它们在使用之前不会解体。",
   vocab=["decay 分解 ↔ decompose；disintegrate 解体 ↔ fall apart",
          "be stored in the dark 避光保存 ＝ particular storage conditions"]),
]
