# -*- coding: utf-8 -*-
"""Passage 1 · How much higher? How much faster? —— 逐题讲解内容。"""

MAP = [
    ("P1–P2", ["百年成绩持续提高", "力量项目 vs 耐力项目", "最重要因素：基因"]),
    ("P3–P6", ["基因只占三分之一", "plyometrics 力量训练", "营养 / 针对性训练"]),
    ("P7–P9", ["biomechanics 生物力学", "Fosbury flop 与器材", "认识仍然基础"]),
]

STRATEGY = [
    ("Q1–6 判断题：先定位时间与主体，再核对“比较方向 / 全称词 / 是否真的提到”。",),
    ("Q7–10 句子填空：ONE WORD，先用介词与冠词预测词性，答案多在引号句内。",),
    ("Q11–13 选择题：先读题干找限定，再回原文找唯一支持句，最后逐项排除。",),
]

SUMMARY = [
    ("判断三陷阱", ["most greatly 比较级", "fully 全称词", "时间范围之外"]),
    ("填空定位点", ["running on their", "increasing power", "lead to injuries"]),
    ("选择题动作", ["题干先限定", "原文找唯一句", "选项逐个排除"]),
]

Q = [
 # ------------------------------------------------------------------ Q1
 dict(n=1, kind="TFNG",
   title="P1 Q1｜date from：把“大约1900”对回原文时间",
   stem="Modern official athletic records date from about 1900.",
   entry=["锚点：official records / about 1900。", "判断题先问：记录从何时开始？"],
   ev="P1 S1: Since the early years of the twentieth century, when the International Athletic "
      "Federation began keeping records, there has been a steady improvement ...",
   logic=["official records ↔ the International Athletic Federation began keeping records。",
          "about 1900 ↔ the early years of the twentieth century（20世纪最初几年）。",
          "主体一致、时间一致 → 支持。"],
   ans="TRUE", ansnote=["时间与主体双对应。", "近似说法≠矛盾。"],
   stitle="P1 Q1｜when 定语从句 + 三个 how 从句",
   sent="Since the early years of the twentieth century, when the International Athletic Federation began "
        "keeping records, there has been a steady improvement in how fast athletes run, how high they jump "
        "and how far they are able to hurl massive objects, themselves included, through space.",
   core="There has been a steady improvement.",
   layers=["Since ... century 是时间状语，划定全文起点。",
           "when 引导定语从句，补充说明这个时间点发生了什么。",
           "how fast / how high / how far 三个从句并列，作 in 的宾语。",
           "themselves included 是插入语，先跳过。"],
   cn="自20世纪初国际田联开始保存记录以来，运动员跑得多快、跳得多高、把重物（包括自己）掷得多远，一直在稳步提升。",
   vocab=["steady 稳定的 ↔ continuous / consistent；hurl 投掷 ↔ throw",
          "date from = 始于；keep records = 保存记录"]),
 # ------------------------------------------------------------------ Q2
 dict(n=2, kind="TFNG",
   title="P1 Q2｜before 把时间推到原文范围之外",
   stem="There was little improvement in athletic performance before the twentieth century.",
   entry=["锚点：before the twentieth century。", "先问：原文写没写“20世纪之前”？"],
   ev="P1 S1: Since the early years of the twentieth century ... there has been a steady improvement. "
      "（全文从20世纪写起，未回溯更早时期）",
   logic=["原文用 Since 划定起点，只谈20世纪以来。",
          "对20世纪之前的成绩既没有肯定，也没有否定。",
          "“没写”不能推成“确实提高很少”。"],
   ans="NOT GIVEN", ansnote=["时间落在原文范围外。", "缺信息，不是矛盾。"],
   stitle="P1 Q2｜破折号插入语与百分比范围",
   sent="For the so-called power events — that require a relatively brief, explosive release of energy, "
        "like the 100-metre sprint and the long jump — times and distances have improved ten to twenty per cent.",
   core="Times and distances have improved ten to twenty per cent.",
   layers=["两个破折号之间是插入语，解释 power events 的定义。",
           "先把插入语整段盖住，主干立刻清楚。",
           "like ... 是举例，不是新信息。",
           "ten to twenty per cent 是范围数字，后面 Q3 要用。"],
   cn="所谓力量型项目——需要相对短暂、爆发式释放能量，比如百米短跑和跳远——其成绩和距离提高了百分之十到二十。",
   vocab=["explosive 爆发式的 ↔ sudden and powerful；brief 短暂的 ↔ short",
          "so-called 所谓的；release of energy = 能量释放"]),
 # ------------------------------------------------------------------ Q3
 dict(n=3, kind="TFNG",
   title="P1 Q3｜most greatly：比较级问“谁提高最多”",
   stem="Performance has improved most greatly in events requiring an intensive burst of energy.",
   entry=["锚点：most greatly + burst of energy。", "题干在做“谁第一”的排序。"],
   ev="P1 S2–S3: For the so-called power events ... times and distances have improved ten to twenty per cent. "
      "In the endurance events the results have been more dramatic.（P1 S5: almost thirty per cent faster）",
   logic=["burst of energy ↔ explosive release of energy ＝ power events。",
          "力量项目 10–20%，耐力项目 more dramatic，近 30%。",
          "所以提高最多的是耐力项目，不是力量项目 → 与题干相反。"],
   ans="FALSE", ansnote=["比较方向被写反。", "两个数字直接对撞。"],
   stitle="P1 Q3｜more dramatic 与 thirty per cent 的比较链",
   sent="In the endurance events the results have been more dramatic. ... In 1999, Morocco's Khalid "
        "Khannouchi set a new world record of 2:05:42, almost thirty per cent faster.",
   core="The results have been more dramatic (almost thirty per cent faster).",
   layers=["more dramatic 是比较级，隐含比较对象＝上一句的 power events。",
           "almost thirty per cent faster 是这个比较的具体数值。",
           "比较级句一定要回头找“比谁”，不能只看形容词。",
           "画 30% > 20%，方向立刻定。"],
   cn="在耐力项目中，结果更为显著。1999年摩洛哥选手创造了2:05:42的世界纪录，几乎快了百分之三十。",
   vocab=["dramatic 显著的 ↔ striking / marked；endurance 耐力 ↔ stamina",
          "intensive burst of energy ＝ explosive release of energy"]),
 # ------------------------------------------------------------------ Q4
 dict(n=4, kind="TFNG",
   title="P1 Q4｜fully explained：全称词一出现就要查",
   stem="Improvements in athletic performance can be fully explained by genetics.",
   entry=["锚点：fully / genetics。", "全称词 fully 是本题唯一考点。"],
   ev="P2 S1: No one theory can explain improvements in performance, but the most important factor "
      "has been genetics.",
   logic=["原文：没有任何单一理论能解释，基因只是“最重要的因素”。",
          "most important ≠ fully explains，仍留有别的因素。",
          "题干把“最重要”升级成“全部”，被原文否定。"],
   ans="FALSE", ansnote=["fully 与 No one theory 直接冲突。", "程度被放大。"],
   stitle="P1 Q4｜No one ... but ... 的让步转折",
   sent="No one theory can explain improvements in performance, but the most important factor has been genetics.",
   core="No one theory can explain improvements, but genetics is the most important factor.",
   layers=["No one theory can ... 是整句的否定前提。",
           "but 之后才是作者真正的立场：基因最重要。",
           "两个分句合起来＝“重要，但不是全部”。",
           "判断题遇到 but，答案几乎总在 but 之后。"],
   cn="没有哪一种理论能解释成绩的提高，但最重要的因素一直是遗传（基因）。",
   vocab=["factor 因素 ↔ element / cause；genetics 遗传学、基因",
          "fully explained by = 完全由……解释（全称）"]),
 # ------------------------------------------------------------------ Q5
 dict(n=5, kind="TFNG",
   title="P1 Q5｜choose his parents：谚语不等于事实陈述",
   stem="The parents of top athletes have often been successful athletes themselves.",
   entry=["锚点：parents + successful athletes。", "题干问“父母本人是否也是运动员”。"],
   ev="P2 S2: 'The athlete must choose his parents carefully,' says Jesus Dapena, a sports scientist at "
      "Indiana University, invoking an oft-cited adage.",
   logic=["原文只是引用一句谚语，强调“基因来自父母”。",
          "全文没有说顶尖运动员的父母本人是不是成功运动员。",
          "相关词出现（parents）≠ 完整关系被给出。"],
   ans="NOT GIVEN", ansnote=["只有基因暗示。", "父母身份未提。"],
   stitle="P1 Q5｜引语 + 同位语 + invoking 非谓语",
   sent="'The athlete must choose his parents carefully,' says Jesus Dapena, a sports scientist at Indiana "
        "University, invoking an oft-cited adage.",
   core="Jesus Dapena says: the athlete must choose his parents carefully.",
   layers=["引号内是被说的话，says + 主语是倒装的引述结构。",
           "a sports scientist ... 是 Dapena 的同位语，可整块跳过。",
           "invoking an oft-cited adage 是现在分词状语，说明“在引用一句老话”。",
           "adage 一词提示：这是比喻，不是数据。"],
   cn="“运动员必须谨慎地选择自己的父母，”印第安纳大学运动科学家 Jesus Dapena 引用了这句常被提起的老话。",
   vocab=["adage 谚语 ↔ saying / proverb；invoke 引用 ↔ cite / refer to",
          "oft-cited = 常被引用的"]),
 # ------------------------------------------------------------------ Q6
 dict(n=6, kind="TFNG",
   title="P1 Q6｜identified early 与 younger age 的等价",
   stem="The growing international importance of athletics means that gifted athletes can be recognised at a younger age.",
   entry=["锚点：international / gifted / younger age。", "三个要素都要在原文找到。"],
   ev="P2 S3: ... but with increasing global participation in athletics — and greater rewards to tempt "
      "athletes — it is more likely that individuals possessing the unique complement of genes for athletic "
      "performance can be identified early.",
   logic=["international importance ↔ increasing global participation。",
          "gifted athletes ↔ individuals possessing the unique complement of genes。",
          "recognised at a younger age ↔ can be identified early。三处都对应。"],
   ans="TRUE", ansnote=["三组同义替换齐全。", "逻辑关系完整。"],
   stitle="P1 Q6｜it is more likely that ... 形式主语句",
   sent="Over the past century, the composition of the human gene pool has not changed appreciably, but with "
        "increasing global participation in athletics — and greater rewards to tempt athletes — it is more "
        "likely that individuals ... can be identified early.",
   core="It is more likely that individuals can be identified early.",
   layers=["but 之前讲基因库没变，是背景，不是考点。",
           "with ... participation 是伴随状语，表示条件。",
           "it 是形式主语，真正主语是后面的 that 从句。",
           "possessing ... 是现在分词后置定语，修饰 individuals。"],
   cn="过去一个世纪，人类基因库的构成没有明显变化，但随着全球参与度提高、奖励增加，具备独特运动基因组合的人更有可能被及早发现。",
   vocab=["appreciably 明显地 ↔ noticeably；tempt 吸引 ↔ attract",
          "identify early = recognise at a younger age"]),
 # ------------------------------------------------------------------ Q7
 dict(n=7, kind="FILL",
   title="P1 Q7｜relying on：找“靠什么取得成绩”",
   stem="According to Professor Yessis, American runners are relying for their current success on ……………",
   entry=["rely on + 空格 → 名词。", "锚点：Yessis / American runners。"],
   ev="P3 S3: Yessis believes that U.S. runners, despite their impressive achievements, are 'running on "
      "their genetics'.",
   logic=["American runners ↔ U.S. runners。",
          "relying ... on ↔ running on（原文用引号做比喻）。",
          "current success ↔ impressive achievements。空格填 on 后的名词。"],
   ans="genetics", ansnote=["ONE WORD。", "照抄原文拼写。"],
   stitle="P1 Q7｜despite 让步 + 引号里的比喻",
   sent="Yessis believes that U.S. runners, despite their impressive achievements, are 'running on their genetics'.",
   core="U.S. runners are running on their genetics.",
   layers=["believes that ... 是宾语从句，主干在从句里。",
           "despite ... achievements 是让步插入语，先盖住。",
           "盖掉插入语后 S + V 立刻清楚：runners are running on ...。",
           "引号表示这是形象说法，含“只吃老本”的贬义。"],
   cn="Yessis 认为，美国跑者尽管成绩亮眼，却是在“靠基因跑步”。",
   vocab=["impressive 令人印象深刻的 ↔ remarkable；achievement 成就 ↔ success",
          "rely on = run on（此处比喻“依赖”）"]),
 # ------------------------------------------------------------------ Q8
 dict(n=8, kind="FILL",
   title="P1 Q8｜develop an athlete's：找被发展的能力",
   stem="Yessis describes a training approach from the former Soviet Union that aims to develop an athlete's ……………",
   entry=["develop an athlete's + 空格 → 名词。", "锚点：former Soviet Union。"],
   ev="P3 S5: ... as well as plyometrics, a technique pioneered in the former Soviet Union. "
      "P4 S1: ... plyometrics focuses on increasing power — the rate at which an athlete can expend energy.",
   logic=["先用 former Soviet Union 定位到 plyometrics。",
          "再顺着 plyometrics 到下一段找它“练什么”。",
          "aims to develop ↔ focuses on increasing。空格填 power。"],
   ans="power", ansnote=["ONE WORD。", "跨段两步定位。"],
   stitle="P1 Q8｜Whereas 让步 + 破折号同位解释",
   sent="Whereas most exercises are designed to build up strength or endurance, plyometrics focuses on "
        "increasing power — the rate at which an athlete can expend energy.",
   core="Plyometrics focuses on increasing power.",
   layers=["Whereas 引导让步／对比状语从句，先读后半句。",
           "主句主语 plyometrics，谓语 focuses on。",
           "破折号后是 power 的同位解释，不是新答案。",
           "at which 定语从句修饰 the rate。"],
   cn="大多数训练旨在增强力量或耐力，而超等长训练关注的是提高“功率”——即运动员释放能量的速率。",
   vocab=["endurance 耐力 ↔ stamina；expend 消耗 ↔ use up / spend",
          "focus on increasing = aim to develop"]),
 # ------------------------------------------------------------------ Q9
 dict(n=9, kind="FILL",
   title="P1 Q9｜links A to B：找因果的结果端",
   stem="Yessis links an inadequate diet to ……………",
   entry=["links ... to + 空格 → 结果名词。", "锚点：inadequate diet（营养不足）。"],
   ev="P5 S4: Few coaches, for instance, understand how deficiencies in trace minerals can lead to injuries.",
   logic=["inadequate diet ↔ deficiencies in trace minerals（微量元素缺乏）。",
          "links ... to ↔ can lead to（因果关系词替换）。",
          "取 lead to 后的名词，注意复数形式。"],
   ans="injuries", ansnote=["ONE WORD，复数。", "照抄原文形式。"],
   stitle="P1 Q9｜how 引导的宾语从句藏因果",
   sent="Few coaches, for instance, understand how deficiencies in trace minerals can lead to injuries.",
   core="Few coaches understand how deficiencies can lead to injuries.",
   layers=["Few 是否定含义的主语：“几乎没有教练懂”。",
           "for instance 是插入语，跳过。",
           "how ... 整段是 understand 的宾语从句。",
           "真正的因果在从句内：deficiencies → injuries。"],
   cn="例如，很少有教练明白微量元素缺乏是如何导致受伤的。",
   vocab=["deficiency 缺乏 ↔ shortage / lack；trace minerals 微量元素",
          "lead to = result in = cause"]),
 # ------------------------------------------------------------------ Q10
 dict(n=10, kind="FILL",
   title="P1 Q10｜the key to：找打破纪录的条件",
   stem="Yessis claims that the key to setting new records is better ……………",
   entry=["better + 空格 → 可被 better 修饰的名词。", "锚点：setting new records。"],
   ev="P6 S3: ... 'but there will be increases even if only by hundredths of a second, as long as our "
      "training continues to improve.'",
   logic=["setting new records ↔ there will be increases（成绩继续提高）。",
          "the key to ↔ as long as（条件关系）。",
          "better ↔ continues to improve。空格填 training。"],
   ans="training", ansnote=["ONE WORD。", "条件句给出答案。"],
   stitle="P1 Q10｜冒号引出直接引语 + as long as 条件",
   sent="He will not predict by how much, however: 'Exactly what the limits are it's hard to say, but there "
        "will be increases even if only by hundredths of a second, as long as our training continues to improve.'",
   core="There will be increases as long as our training continues to improve.",
   layers=["冒号前是转述，冒号后才是原话。",
           "Exactly what the limits are 是前置的宾语从句，属让步。",
           "but 之后是重点：一定会有提高。",
           "as long as 引导条件状语从句，答案就在这里。"],
   cn="不过他不肯预测提高多少：“极限究竟在哪里很难说，但只要训练不断改进，成绩就会提高，哪怕只有百分之一秒。”",
   vocab=["predict 预测 ↔ forecast；hundredths of a second 百分之一秒",
          "as long as = provided that（只要）"]),
 # ------------------------------------------------------------------ Q11
 dict(n=11, kind="MCQ",
   title="P1 Q11｜biomechanics films 让教练能做什么",
   stem="Biomechanics films are proving particularly useful because they enable trainers to",
   options=["highlight areas for improvement in athletes.", "assess the fitness levels of athletes.",
            "select top athletes.", "predict the success of athletes."],
   entry=["锚点：films / enable trainers to。", "原文要给出“拍完之后能说什么”。"],
   ev="P7 S3: By applying Newton's laws to these motions, 'we can say that this athlete's run is not fast "
      "enough; that this one is not using his arms strongly enough during take-off,' says Dapena.",
   logic=["原文两句引语都在指出“哪里还不够好”。",
          "not fast enough / not using his arms strongly enough ＝ 待改进之处。",
          "B 体能测评、C 选材、D 预测成绩，原文都未提。"],
   ans="A", ansnote=["highlight areas for", "improvement 指出不足"],
   stitle="P1 Q11｜By applying ... 状语 + 两个 that 从句",
   sent="By applying Newton's laws to these motions, 'we can say that this athlete's run is not fast enough; "
        "that this one is not using his arms strongly enough during take-off,' says Dapena, who uses these "
        "methods to help high jumpers.",
   core="We can say that this athlete's run is not fast enough.",
   layers=["By applying ... 是方式状语，说明凭什么下判断。",
           "两个 that 从句并列，都是 say 的宾语。",
           "分号只是并列，不是新话题。",
           "who ... 非限定定语从句补充 Dapena 的身份。"],
   cn="通过把牛顿定律用于这些动作，“我们可以说这名运动员跑得不够快，那名运动员起跳时手臂用力不足，”Dapena 说，他用这些方法帮助跳高运动员。",
   vocab=["highlight 指出、突出 ↔ point out / identify；take-off 起跳",
          "areas for improvement = 不足之处（＝原文两处 not ... enough）"]),
 # ------------------------------------------------------------------ Q12
 dict(n=12, kind="MCQ",
   title="P1 Q12｜理论模型对 Fosbury flop 起了什么作用",
   stem="Biomechanics specialists used theoretical models to",
   options=["soften the Fosbury flop.", "create the Fosbury flop.",
            "correct the Fosbury flop.", "explain the Fosbury flop."],
   entry=["锚点：biomechanics specialists / models。", "问的是“模型用来干什么”。"],
   ev="P8 S4: That understanding took the later analysis of biomechanics specialists, who put their minds "
      "to comprehending something that was too complex and unorthodox ever to have been invented through "
      "their own mathematical simulations.",
   logic=["专家做的是 comprehending＝理解、解释这个动作。",
          "too ... ever to have been invented 明确否定“模型能发明它” → B 错。",
          "原文没有 soften／correct 的意思 → A、C 排除。"],
   ans="D", ansnote=["explain the flop", "模型只负责解释"],
   stitle="P1 Q12｜too ... to 的否定含义",
   sent="That understanding took the later analysis of biomechanics specialists, who put their minds to "
        "comprehending something that was too complex and unorthodox ever to have been invented through "
        "their own mathematical simulations.",
   core="The understanding took the later analysis of biomechanics specialists.",
   layers=["who ... 定语从句说明专家做了什么：comprehending（理解）。",
           "something that was too ... to have been invented：太复杂，不可能被发明出来。",
           "too ... to 结构本身就是否定，别读成肯定。",
           "invented 的主体是模型，不是 Fosbury。"],
   cn="这种理解要靠后来生物力学专家的分析，他们努力去理解一个过于复杂、过于反常规、根本不可能由他们自己的数学模拟发明出来的动作。",
   vocab=["comprehend 理解 ↔ understand / explain；unorthodox 非常规的 ↔ unusual",
          "too ... ever to have been invented ＝ 不可能被发明出来"]),
 # ------------------------------------------------------------------ Q13
 dict(n=13, kind="MCQ",
   title="P1 Q13｜Raglin 认为目前的认识处于什么水平",
   stem="John S. Raglin believes our current knowledge of athletics is",
   options=["mistaken.", "basic.", "diverse.", "theoretical."],
   entry=["锚点：Raglin / our understanding。", "找他对“认知水平”的定性词。"],
   ev="P9 S4: So many variables enter into the equation, and our understanding in many cases is fundamental. "
      "We've got a long way to go.",
   logic=["fundamental 在此指“还停留在基础阶段”，不是“根本重要”。",
          "下一句 a long way to go 印证：路还很长。",
          "他没有说认识是错的（A）、多样的（C）或纯理论的（D）。"],
   ans="B", ansnote=["basic 基础的", "fundamental = basic"],
   stitle="P1 Q13｜fundamental 的语境义要由下一句锁定",
   sent="So many variables enter into the equation, and our understanding in many cases is fundamental. "
        "We've got a long way to go.",
   core="Our understanding is fundamental (basic).",
   layers=["So many variables ... 说明影响因素太多。",
           "and 连接的第二个分句才是结论句。",
           "in many cases 是范围限定，不影响判断。",
           "下一句 a long way to go 是关键佐证，必须连读。"],
   cn="太多变量进入这个方程，我们在很多情况下的理解还很初步。我们要走的路还很长。",
   vocab=["variable 变量 ↔ factor；fundamental 基础的 ↔ basic",
          "have a long way to go = 还差得远"]),
]
