# -*- coding: utf-8 -*-
"""第三节课词汇与长难句讲解（打印资料附录）。

VOCAB[key] = [(词汇·核心义, IELTS同义替换, 记忆方法, 迁移例句 + 中文翻译), ...]
LONG[key]  = [(原句, 原句理解翻译, 句子主干, 简化后的主干意思), ...]
"""

VOCAB = {
"P0": [
 ("substitute /ˈsʌbstɪtjuːt/ 替代品；代替", "replacement / alternative / something used instead of",
  "sub-（下面）＋stitute（放）→ 放到别人的位置上。",
  "The first plastics were developed as a substitute for natural rubber. 最早的塑料是作为天然橡胶的替代品研制出来的。"),
 ("compound /ˈkɒmpaʊnd/ 化合物", "substance made of two or more elements / chemical combination",
  "com-（共同）＋pound（放）→ 合在一起的物质。",
  "Rubber is a compound containing large molecules. 橡胶是一种含有大分子的化合物。"),
 ("bonding /ˈbɒndɪŋ/ 成键；结合", "joining / linking / chemical connection",
  "bond＝纽带、化学键。",
  "The same bonding principle is the basis of plastics. 同样的成键原理是塑料的基础。"),
 ("decline /dɪˈklaɪn/ 减少；下降", "fall / decrease / go down / become less available",
  "de-（向下）＋cline（倾斜）。",
  "Supplies of ivory were declining in the 1860s. 19世纪60年代象牙的供应在减少。"),
 ("dissolve /dɪˈzɒlv/ 溶解", "melt into a liquid / break down in liquid",
  "dis-（分开）＋solve（松开）→ 化开。",
  "Celluloid was made by dissolving cellulose in a solution. 赛璐珞是把纤维素溶解在溶液中制成的。"),
 ("take off 起飞；兴起", "become successful / grow rapidly / start to develop",
  "飞机起飞＝事业起步。",
  "The film industry could never have taken off without it. 没有它电影业根本不可能起步。"),
 ("insulator /ˈɪnsjuleɪtə/ 绝缘体", "material that does not conduct electricity / insulating material",
  "insulate＝隔离；名词即“隔离体”。",
  "Bakelite was a good insulator. Bakelite 是良好的绝缘体。"),
 ("resistant to /rɪˈzɪstənt/ 耐……的；抗……的", "not damaged by / able to withstand / proof against",
  "resist（抵抗）＋-ant。",
  "It was resistant to water and acid. 它耐水耐酸。"),
 ("domestic /dəˈmestɪk/ 家用的；国内的", "household / home / used in the house",
  "阅读中先按语境判断是“家用”还是“国内”。",
  "It was used in a variety of domestic items. 它被用于各种家用物品。"),
 ("rigid /ˈrɪdʒɪd/ 硬质的；坚硬的", "stiff / hard / not flexible",
  "与 rigorous 同根，都有“不弯”的意思。",
  "Rigid PVC is suitable for drains and gutters. 硬质 PVC 适用于排水管和檐槽。"),
 ("fireproof /ˈfaɪəpruːf/ 防火的", "fire-resistant / not able to burn / safe from fire",
  "fire＋proof（防……的），同类还有 waterproof。",
  "Rigid PVC is a fireproof plastic. 硬质 PVC 是一种防火塑料。"),
 ("friction /ˈfrɪkʃn/ 摩擦（力）", "rubbing / resistance between surfaces",
  "想象两个面互相摩擦。",
  "Teflon produces very little friction. 特氟龙产生的摩擦极小。"),
 ("resemble /rɪˈzembl/ 类似于", "be like / look like / be similar to",
  "re-＋semble（相似，见 similar）。",
  "Polystyrene resembles glass. 聚苯乙烯像玻璃。"),
 ("foam /fəʊm/ 泡沫", "light spongy material / bubbly material",
  "洗发水的泡沫就是 foam。",
  "Polyurethane was commonly produced as a foam. 聚氨酯通常被制成泡沫。"),
 ("indestructibility /ˌɪndɪstrʌktəˈbɪləti/ 不可摧毁性", "being impossible to destroy / extreme durability",
  "in-（不）＋destruct（毁）＋-ibility。",
  "Its indestructibility is its greatest disadvantage. 它的不可摧毁性正是它最大的缺点。"),
 ("call for 需要；要求", "require / need / demand",
  "字面“呼唤”，引申为“需要”。",
  "Different types of plastic call for different treatments. 不同种类的塑料需要不同的处理方式。"),
 ("biodegradable /ˌbaɪəʊdɪˈɡreɪdəbl/ 可生物降解的", "able to be broken down by bacteria / decomposable",
  "bio（生物）＋degrade（降解）＋-able。",
  "Plastics can be made biodegradable. 塑料可以被制成可生物降解的。"),
 ("disintegrate /dɪsˈɪntɪɡreɪt/ 解体；碎裂", "fall apart / break into pieces / decompose",
  "dis-＋integrate（整合）→ 不再整体。",
  "Bottles must not disintegrate before they have been used. 瓶子不能在使用前就解体。"),
],
"P1": [
 ("steady /ˈstedi/ 稳定的；持续的", "continuous / consistent / regular / not changing suddenly",
  "steady 与 stay 同源，“待得住”＝稳定。",
  "There has been a steady improvement in athletic performance. 运动成绩一直在稳步提高。"),
 ("hurl /hɜːl/ 投掷；用力扔", "throw / fling / cast / send through the air with force",
  "发音像“猛地一甩”，力度感很强。",
  "Athletes are able to hurl massive objects through space. 运动员能把重物掷向远处。"),
 ("explosive /ɪkˈspləʊsɪv/ 爆发式的", "sudden and powerful / intensive / a quick burst of",
  "explode（爆炸）＋-ive，形容瞬间释放。",
  "Power events require an explosive release of energy. 力量型项目需要爆发式的能量释放。"),
 ("endurance /ɪnˈdjʊərəns/ 耐力", "stamina / staying power / ability to keep going",
  "endure（忍耐）＋-ance，能撑住的能力。",
  "In the endurance events the results have been more dramatic. 在耐力项目中结果更为显著。"),
 ("dramatic /drəˈmætɪk/ 显著的；巨大的", "striking / marked / significant / very noticeable",
  "戏剧性的变化＝幅度大到显眼。",
  "The improvement was more dramatic than in power events. 提高幅度比力量项目更显著。"),
 ("appreciably /əˈpriːʃəbli/ 明显地", "noticeably / significantly / to a noticeable degree",
  "appreciate 有“察觉”义，副词即“可察觉地”。",
  "The gene pool has not changed appreciably. 基因库没有明显变化。"),
 ("invoke /ɪnˈvəʊk/ 引用；援引", "cite / refer to / call upon / quote",
  "in-（向内）＋voc（声音）→ 把别人的话搬出来。",
  "He invoked an oft-cited adage about parents. 他引用了一句常被提起的关于父母的老话。"),
 ("adage /ˈædɪdʒ/ 谚语；格言", "saying / proverb / well-known phrase",
  "与 age 有关：流传了很久的话。",
  "'Choose your parents carefully' is an old adage. “谨慎选择父母”是一句老话。"),
 ("duplicate /ˈdjuːplɪkeɪt/ 复制；重现", "copy / reproduce / repeat exactly",
  "du-（二）＋plic（折叠）→ 做出第二份。",
  "Strength training should duplicate the running action. 力量训练应当复制跑步的动作。"),
 ("expend /ɪkˈspend/ 消耗；花费", "use up / spend / consume",
  "ex-（出）＋pend（花）→ 花出去。",
  "Power is the rate at which an athlete can expend energy. 功率是运动员释放能量的速率。"),
 ("deficiency /dɪˈfɪʃnsi/ 缺乏；不足", "shortage / lack / inadequate supply of",
  "deficient（不足的）的名词形式。",
  "Deficiencies in trace minerals can lead to injuries. 微量元素缺乏会导致受伤。"),
 ("digitize /ˈdɪdʒɪtaɪz/ 数字化", "convert into data / record in digital form",
  "digit（数字）＋-ize，把动作变成数据。",
  "A biomechanic digitizes an athlete's performance. 生物力学家把运动员的动作数字化。"),
 ("unorthodox /ʌnˈɔːθədɒks/ 非常规的", "unconventional / unusual / not traditional",
  "un-＋orthodox（正统的）→ 不按常规。",
  "The Fosbury flop was a highly unorthodox move. 背越式跳高是一个极不合常规的动作。"),
 ("vexingly /ˈveksɪŋli/ 令人头疼地", "annoyingly / frustratingly / troublingly",
  "vex＝使烦恼，副词即“烦人地”。",
  "Athletics is a vexingly complex issue. 田径是一个复杂得令人头疼的问题。"),
 ("fundamental /ˌfʌndəˈmentl/ 基础的；初步的", "basic / elementary / at an early stage",
  "阅读中要看语境：此处是“还很初步”，不是“至关重要”。",
  "Our understanding in many cases is fundamental. 我们在许多情况下的理解还很初步。"),
],
"P2": [
 ("terrestrial /təˈrestriəl/ 陆生的", "living on land / land-based / not aquatic",
  "terra＝土地（terrace 露台）。",
  "Terrestrial mammals take these senses for granted. 陆生哺乳动物把这些感官视为理所当然。"),
 ("degenerate /dɪˈdʒenəreɪt/ 退化", "deteriorate / get worse / become underdeveloped",
  "de-（向下）＋gener（产生）→ 越长越差。",
  "The nerves serving taste buds have degenerated. 为味蕾服务的神经已经退化。"),
 ("rudimentary /ˌruːdɪˈmentri/ 未充分发育的", "underdeveloped / basic / very simple",
  "rudiment＝雏形，仍停在雏形阶段。",
  "These nerves are rudimentary in most species. 这些神经在多数物种中发育不全。"),
 ("captive /ˈkæptɪv/ 圈养的；被捕获的", "kept in captivity / not free / in a zoo or tank",
  "capture（捕获）的形容词。",
  "Trainers of captive dolphins report frequent contact. 圈养海豚的训练员报告它们常有接触。"),
 ("free-ranging /ˌfriː ˈreɪndʒɪŋ/ 野外自由活动的", "living in the wild / not captive / roaming freely",
  "free＋range（活动范围）。",
  "Free-ranging whales were filmed off Argentina. 野生鲸鱼在阿根廷外海被拍摄到。"),
 ("courtship /ˈkɔːtʃɪp/ 求偶", "mating behaviour / attracting a partner",
  "court 作动词有“追求”义。",
  "Touching is part of the courtship ritual. 触碰是求偶仪式的一部分。"),
 ("stereoscopic /ˌsteriəˈskɒpɪk/ 立体的", "three-dimensional / giving depth perception",
  "stereo（立体声）同根，双眼合成深度。",
  "Baleen whales probably lack stereoscopic vision. 须鲸很可能没有立体视觉。"),
 ("keen /kiːn/ 敏锐的", "sharp / acute / exceptional / very good",
  "keen eyesight＝眼力好，考试常与 exceptional 互换。",
  "The bottlenose dolphin has extremely keen vision. 宽吻海豚视力极其敏锐。"),
 ("turbid /ˈtɜːbɪd/ 浑浊的", "muddy / cloudy / not clear",
  "与 disturb 同根：被搅动过的水。",
  "Some dolphins live in turbid rivers. 一些海豚生活在浑浊的河流中。"),
 ("inhabit /ɪnˈhæbɪt/ 栖息于", "live in / occupy / be found in",
  "habitat（栖息地）的动词。",
  "Vision is more useful to species inhabiting clear waters. 视觉对生活在清水中的物种更有用。"),
 ("compensate for /ˈkɒmpenseɪt/ 弥补", "make up for / offset / balance out",
  "com-＋pens（称重）→ 把天平配平。",
  "Weak vision is compensated for by good hearing. 视觉弱由良好的听觉来弥补。"),
 ("acoustic /əˈkuːstɪk/ 听觉的；声音的", "hearing / relating to sound",
  "acoustic guitar＝原声吉他，与“声”有关。",
  "Cetaceans have a well-developed acoustic sense. 鲸类的听觉非常发达。"),
 ("repertoire /ˈrepətwɑː/ 曲目；声音范围", "range of sounds / variety they can produce",
  "原指演员的“保留剧目”，此处指会发的声音种类。",
  "Large baleen whales are limited in their repertoire. 大型须鲸的发声种类有限。"),
 ("utterance /ˈʌtərəns/ 发声；话语", "sound / call / vocalisation",
  "utter（说出）的名词。",
  "Humpback whales produce complex utterances. 座头鲸能发出复杂的鸣叫。"),
 ("echolocation /ˌekəʊləʊˈkeɪʃn/ 回声定位", "finding objects by sound echoes",
  "echo（回声）＋location（定位）。",
  "Many species forage for food using echolocation. 许多物种利用回声定位觅食。"),
],
"P3": [
 ("perspective /pəˈspektɪv/ 透视法", "a way of showing depth / drawing convention",
  "per-（透过）＋spect（看）→ 透过画面看纵深。",
  "Blind people can appreciate the use of perspective. 盲人能理解透视法的运用。"),
 ("literal /ˈlɪtərəl/ 字面的；如实的", "exact / direct / not symbolic",
  "letter（字母）同根：照字面。",
  "Pictures are more than literal representations. 图画不只是如实的再现。"),
 ("initiative /ɪˈnɪʃətɪv/ 主动；首创", "of her own accord / without being asked",
  "initial（最初的）＋-ive，自己先动。",
  "She decided on her own initiative to draw a wheel. 她自发决定画一个轮子。"),
 ("taken aback /əˈbæk/ 吃惊的", "surprised / startled / astonished",
  "像被往后推了一下。",
  "I was taken aback by her drawing. 她的画让我大吃一惊。"),
 ("metaphorical /ˌmetəˈfɒrɪkl/ 隐喻的", "symbolic / figurative / not literal",
  "metaphor（比喻）的形容词。",
  "They described the curves as metaphorical ways of suggesting motion. 他们说这些曲线是暗示运动的隐喻方式。"),
 ("idiosyncratic /ˌɪdiəsɪŋˈkrætɪk/ 特异的；个人化的", "personal / peculiar / individual",
  "idio-＝个人的（idiom 习语）。",
  "Were they merely idiosyncratic marks? 它们只是个人化的随意记号吗？"),
 ("apt /æpt/ 恰当的", "suitable / appropriate / fitting",
  "adapt（适应）同根，贴合的。",
  "He tested whether the lines were apt ways of showing movement. 他测试这些线条是否是表现运动的恰当方式。"),
 ("perimeter /pəˈrɪmɪtə/ 周边；轮圈", "rim / outer edge / boundary",
  "peri-（周围）＋meter（测量）。",
  "Spokes extended beyond the wheel's perimeter. 轮辐伸出了轮圈之外。"),
 ("signify /ˈsɪɡnɪfaɪ/ 表示；意味着", "indicate / mean / suggest / stand for",
  "sign（记号）＋-ify。",
  "Extending spokes signified that the wheel had its brakes on. 伸出的轮辐表示轮子在刹车。"),
 ("consensus /kənˈsensəs/ 共识", "general agreement / shared view",
  "con-（共同）＋sens（感觉）。",
  "The consensus among the sighted was barely higher. 明眼人之间的共识度只高出一点点。"),
 ("distinctive /dɪˈstɪŋktɪv/ 各不相同的；有区别的", "different / characteristic / easy to tell apart",
  "distinct（清楚可辨）＋-ive。",
  "Subjects assigned distinctive motions to each wheel. 受试者给每个轮子指派了不同的运动。"),
 ("ascribe /əˈskraɪb/ 把……归于", "assign / attribute / link to",
  "a-＋scribe（写）→ 把名字写到某处。",
  "94% ascribed happy to the circle. 94%的人把“快乐”归给圆形。"),
 ("deem /diːm/ 认为", "consider / regard / judge to be",
  "与 doom 同源，作出判定。",
  "All our subjects deemed the circle soft. 我们所有的受试者都认为圆形是柔软的。"),
 ("resemble /rɪˈzembl/ 相似于", "be similar to / look like / be close to",
  "re-＋semble（相似，见 similar）。",
  "Their choices closely resembled those of the sighted. 他们的选择与明眼人的非常相似。"),
 ("symbolism /ˈsɪmbəlɪzəm/ 象征意义", "what a shape stands for / symbolic meaning",
  "symbol＋-ism。",
  "They explored the symbolism behind shapes such as hearts. 他们研究心形之类形状背后的象征意义。"),
],
"P4": [
 ("deceptively /dɪˈseptɪvli/ 具有迷惑性地", "in a misleading way / seeming simpler than it is",
  "deceive（欺骗）的副词。",
  "It had a deceptively simple heading. 它有一个看似简单的标题。"),
 ("undertaking /ˌʌndəˈteɪkɪŋ/ 事业；尝试", "venture / project / task",
  "undertake（着手做）的名词。",
  "It was a brave undertaking at the time. 在当时这是一项勇敢的尝试。"),
 ("faultless /ˈfɔːltləs/ 无可挑剔的", "perfect / excellent / without flaws",
  "fault（缺点）＋-less。",
  "His background was faultless. 他的履历无可挑剔。"),
 ("subsequently /ˈsʌbsɪkwəntli/ 随后", "later / afterwards / after that",
  "sub-＋sequ（跟随）→ 跟在后面。",
  "He subsequently secured a job as chief statistician. 他随后谋得首席统计员的职位。"),
 ("tedium /ˈtiːdiəm/ 单调乏味", "boredom / dullness / monotony",
  "tedious（乏味的）的名词。",
  "He grew bored with the tedium of transcribing reports. 他厌倦了抄录报告的单调工作。"),
 ("come to a head", "reach a crisis / become critical / reach a turning point",
  "问题“顶到头”＝到了临界点。",
  "This problem came to a head in 1859. 这个问题在1859年到了临界点。"),
 ("stir up /stɜː/ 激起", "provoke / arouse / cause strong feelings",
  "搅动情绪。",
  "FitzRoy stirred up feelings even further. FitzRoy 进一步激起了公众情绪。"),
 ("standardised /ˈstændədaɪzd/ 标准化的", "uniform / consistent / reliable",
  "standard＋-ised，统一规格。",
  "He issued ships with standardised instruments. 他给船只配发标准化仪器。"),
 ("ingenious /ɪnˈdʒiːniəs/ 巧妙的", "clever / inventive / well-designed",
  "与 genius 同根，别与 ingenuous（天真的）混。",
  "An ingenious system of flags was used. 使用了一套巧妙的旗语系统。"),
 ("hoist /hɔɪst/ 升起", "raise / lift / put up",
  "把旗“吊”上去。",
  "The flags were hoisted up high. 旗帜被高高升起。"),
 ("vessel /ˈvesl/ 船只", "boat / ship / craft",
  "也可指“容器”，阅读中按语境判断。",
  "The owners of fishing vessels were not supportive. 渔船船主并不支持。"),
 ("indisputable /ˌɪndɪˈspjuːtəbl/ 无可争辩的", "undeniable / beyond doubt / certain",
  "in-＋dispute（争论）＋-able。",
  "It is indisputable that he was ahead of his time. 无可争辩，他走在了时代前面。"),
 ("towering /ˈtaʊərɪŋ/ 杰出的；卓越的", "outstanding / leading / very important",
  "像高塔一样突出。",
  "He is recognised as a towering figure in meteorology. 他被公认为气象学中的杰出人物。"),
 ("prematurely /ˌpreməˈtʃʊəli/ 过早地", "too early / before the expected time",
  "pre-（提前）＋mature（成熟）。",
  "He died prematurely. 他过早地去世了。"),
 ("legacy /ˈleɡəsi/ 遗产；留下的影响", "what someone leaves behind / lasting influence",
  "与 legal 同根，原指遗赠。",
  "But his legacy lives on. 但他留下的影响延续至今。"),
],
}

LONG = {
"P0": [
 ("Chemically, rubber is a polymer—a compound containing large molecules that are formed by the bonding "
  "of many smaller, simpler units, repeated over and over again.",
  "从化学角度看，橡胶是一种聚合物——即由许多更小更简单的单元反复成键而形成大分子的化合物。",
  "Rubber is a polymer.",
  "橡胶是一种聚合物。"),
 ("In the 1860s, $10,000 was offered to anybody who could replace ivory—supplies of which were declining—"
  "with something equally good as a material for making billiard balls.",
  "19世纪60年代，有人悬赏一万美元，奖给能用同样好的材料替代象牙（其供应正在减少）来制造台球的人。",
  "$10,000 was offered to anybody who could replace ivory.",
  "谁能替代象牙就能拿到一万美元。"),
 ("But perhaps the best-known celluloid product was photographic film, without which the film industry "
  "could never have taken off at the end of the 19th century.",
  "但也许最著名的赛璐珞产品是照相胶片；没有它，电影业在19世纪末根本不可能起步。",
  "The best-known celluloid product was photographic film.",
  "赛璐珞最著名的产品是照相胶片。"),
 ("Baekeland called it Bakelite, and it was the first of the thermosets—plastics that can be cast and "
  "moulded while hot, but cannot be softened by heat and reshaped once they have set.",
  "Baekeland 把它称作 Bakelite；它是第一种热固性塑料——这类塑料受热时可浇铸成型，"
  "但一旦定型就无法再受热软化和重塑。",
  "It was the first of the thermosets.",
  "它是第一种热固性塑料。"),
 ("A small change in the starting material—replacing a hydrogen atom in ethylene with a chlorine atom—"
  "produced rigid PVC (polyvinyl chloride), a fireproof plastic suitable for drains and gutters.",
  "起始材料上的一个小改动——把乙烯中的一个氢原子换成氯原子——制造出了硬质 PVC，"
  "这是一种适用于排水管和檐槽的防火塑料。",
  "A small change produced rigid PVC.",
  "一个小改动做出了硬质 PVC。"),
 ("Nor is it very easy to recycle plastics, as different types of plastic are often found in the same "
  "items and call for different treatments.",
  "塑料也不太容易回收，因为同一件物品中往往含有不同种类的塑料，而它们需要不同的处理方式。",
  "It is not very easy to recycle plastics.",
  "塑料回收并不容易。"),
 ("Plastics can be made biodegradable by incorporating into their structure a material such as starch, "
  "which is attacked by bacteria and causes the plastic to fall apart.",
  "通过在结构中加入淀粉之类的材料，可以使塑料变得可生物降解；这种材料会被细菌侵蚀，并使塑料散架。",
  "Plastics can be made biodegradable by incorporating starch.",
  "加入淀粉能让塑料降解。"),
],
"P1": [
 ("Since the early years of the twentieth century, when the International Athletic Federation began keeping "
  "records, there has been a steady improvement in how fast athletes run, how high they jump and how far "
  "they are able to hurl massive objects, themselves included, through space.",
  "自20世纪初国际田径联合会开始保存记录以来，运动员跑得多快、跳得多高、能把包括自身在内的重物掷得多远，"
  "一直在稳步提高。",
  "There has been a steady improvement.",
  "成绩一直在稳步提高。"),
 ("Over the past century, the composition of the human gene pool has not changed appreciably, but with "
  "increasing global participation in athletics — and greater rewards to tempt athletes — it is more likely "
  "that individuals possessing the unique complement of genes for athletic performance can be identified early.",
  "过去一个世纪人类基因库的构成没有明显变化，但随着全球参与度提高、奖励增加，"
  "具备独特运动基因组合的人更有可能被及早发现。",
  "It is more likely that individuals can be identified early.",
  "有天赋的人更可能被及早发现。"),
 ("Whereas most exercises are designed to build up strength or endurance, plyometrics focuses on increasing "
  "power — the rate at which an athlete can expend energy.",
  "大多数训练旨在增强力量或耐力，而超等长训练关注的是提高功率——即运动员释放能量的速率。",
  "Plyometrics focuses on increasing power.",
  "超等长训练练的是功率。"),
 ("By applying Newton's laws to these motions, 'we can say that this athlete's run is not fast enough; that "
  "this one is not using his arms strongly enough during take-off,' says Dapena, who uses these methods to "
  "help high jumpers.",
  "通过把牛顿定律用于这些动作，“我们可以说这名运动员跑得不够快，那名运动员起跳时手臂用力不足，”"
  "Dapena 说，他用这些方法帮助跳高运动员。",
  "We can say that this athlete's run is not fast enough.",
  "分析能指出运动员哪里还不够好。"),
 ("That understanding took the later analysis of biomechanics specialists, who put their minds to "
  "comprehending something that was too complex and unorthodox ever to have been invented through their "
  "own mathematical simulations.",
  "这种理解要靠后来生物力学专家的分析，他们努力去理解一个过于复杂、过于反常规、"
  "根本不可能由他们自己的数学模拟发明出来的动作。",
  "That understanding took the later analysis of biomechanics specialists.",
  "是专家事后分析才解释清楚的。"),
 ("So many variables enter into the equation, and our understanding in many cases is fundamental.",
  "太多变量进入这个方程，我们在许多情况下的理解还很初步。",
  "Our understanding is fundamental.",
  "我们的认识还很基础。"),
],
"P2": [
 ("Similarly, although at least some cetaceans have taste buds, the nerves serving these have degenerated "
  "or are rudimentary.",
  "同样，尽管至少有些鲸类拥有味蕾，但为这些味蕾服务的神经已经退化或发育不全。",
  "The nerves have degenerated or are rudimentary.",
  "连接味蕾的神经已经退化。"),
 ("However, the position of the eyes so restricts the field of vision in baleen whales that they probably "
  "do not have stereoscopic vision.",
  "然而，眼睛的位置极大地限制了须鲸的视野，以至于它们很可能没有立体视觉。",
  "The position of the eyes restricts the field of vision.",
  "眼睛位置限制了视野。"),
 ("Eye position in freshwater dolphins, which often swim on their side or upside down while feeding, "
  "suggests that what vision they have is stereoscopic forward and upward.",
  "淡水海豚常常侧游或倒着游进食；它们的眼睛位置表明，其视觉是向前向上的立体视觉。",
  "Eye position suggests that their vision is stereoscopic forward and upward.",
  "眼睛位置说明它们的立体视觉朝前朝上。"),
 ("For example, vision is obviously more useful to species inhabiting clear open waters than to those "
  "living in turbid rivers and flooded plains.",
  "例如，视觉显然对栖息于清澈开阔水域的物种更有用，而对生活在浑浊河流和泛滥平原中的物种用处较小。",
  "Vision is more useful to species inhabiting clear open waters.",
  "水越清，视觉越有用。"),
 ("Although the senses of taste and smell appear to have deteriorated, and vision in water appears to be "
  "uncertain, such weaknesses are more than compensated for by cetaceans' well-developed acoustic sense.",
  "尽管味觉和嗅觉似乎已退化、水中视觉也不确定，但这些弱点被鲸类高度发达的听觉充分弥补了。",
  "Such weaknesses are compensated for by their acoustic sense.",
  "听觉弥补了其他感官的不足。"),
 ("Toothed species in general employ more of the frequency spectrum, and produce a wider variety of sounds, "
  "than baleen species.",
  "总体而言，齿鲸使用的频谱范围比须鲸更宽，发出的声音种类也更多。",
  "Toothed species employ more of the spectrum and produce more sounds than baleen species.",
  "齿鲸的声音比须鲸更丰富。"),
],
"P3": [
 ("From a number of recent studies, it has become clear that blind people can appreciate the use of "
  "outlines and perspectives to describe the arrangement of objects and other surfaces in space.",
  "从近来的一些研究可以清楚看出，盲人能够理解用轮廓和透视来描述物体及其他表面在空间中排列的方式。",
  "It has become clear that blind people can appreciate outlines and perspectives.",
  "盲人能理解轮廓和透视。"),
 ("This fact was drawn to my attention dramatically when a blind woman in one of my investigations decided "
  "on her own initiative to draw a wheel as it was spinning.",
  "当我研究中的一位盲人女性自发决定画一个正在旋转的轮子时，这一事实戏剧性地引起了我的注意。",
  "This fact was drawn to my attention when a blind woman decided to draw a spinning wheel.",
  "一位盲人自发画旋转的轮子，让我注意到这件事。"),
 ("Most guessed that the curved spokes indicated that the wheel was spinning steadily; the wavy spokes, "
  "they thought, suggested that the wheel was wobbling; and the bent spokes were taken as a sign that the "
  "wheel was jerking.",
  "多数人猜测：弯曲轮辐表示平稳旋转；他们认为波浪形轮辐表示摇晃；折线轮辐则被视为顿挫的标志。",
  "Curved spokes indicated steady spinning; wavy spokes suggested wobbling; bent spokes meant jerking.",
  "三种画法对应三种运动。"),
 ("Evidently, however, the blind not only figured out meanings for each line of motion, but as a group they "
  "generally came up with the same meaning at least as frequently as did sighted subjects.",
  "然而显然，盲人不仅弄清了每种运动线的含义，而且作为一个群体，"
  "他们得出相同含义的频率至少不低于明眼受试者。",
  "The blind figured out meanings and came up with the same meaning as frequently as sighted subjects.",
  "盲人的理解不比明眼人差。"),
 ("With Chang Hong Liu, a doctoral student from China, I have begun exploring how well blind people "
  "understand the symbolism behind shapes such as hearts that do not directly represent their meaning.",
  "我与来自中国的博士生刘长虹一起，开始研究盲人在多大程度上理解心形这类并不直接表示其含义的形状"
  "背后的象征意义。",
  "I have begun exploring how well blind people understand the symbolism behind shapes.",
  "研究盲人对抽象形状象征义的理解。"),
 ("When we tested four totally blind volunteers using the same list, we found that their choices closely "
  "resembled those made by the sighted subjects.",
  "当我们用同一份清单测试四位全盲志愿者时，我们发现他们的选择与明眼受试者的选择非常相似。",
  "We found that their choices closely resembled those of the sighted subjects.",
  "盲人的选择与明眼人很相似。"),
],
"P4": [
 ("It was a brave undertaking, because in those days predicting the weather had gained a reputation similar "
  "to astrology or fortune-telling.",
  "这是一项勇敢的尝试，因为在那个年代，预测天气已经落得与占星术或算命相似的名声。",
  "It was a brave undertaking because forecasting had gained a bad reputation.",
  "当时做预报名声不好，所以很冒险。"),
 ("His background was faultless, most famously his captaining of the ship HMS Beagle on Charles Darwin's "
  "voyage around the world, which eventually led to the publication of Darwin's well-known book On the "
  "Origin of Species.",
  "他的履历无可挑剔，最著名的是他在达尔文环球航行中担任小猎犬号船长，"
  "那次航行最终促成了《物种起源》的出版。",
  "His background was faultless.",
  "他的履历非常出色。"),
 ("However, the British Government was not impressed with the idea of collecting weather reports and "
  "establishing a weather forecast, and the suggestion by one Member of Parliament for this was met with "
  "laughter from the other MPs.",
  "然而，英国政府对收集天气报告、建立天气预报的想法并不感兴趣，"
  "一位议员就此提出的建议还遭到其他议员的哄笑。",
  "The Government was not impressed with the idea of establishing a weather forecast.",
  "政府并不支持做天气预报。"),
 ("The approach of an incoming storm could be recognised, and from London, FitzRoy could telegraph warnings "
  "to ports on the coast, where an ingenious system of flags was hoisted up high for passing ships to read.",
  "逼近风暴的到来可以被识别出来，FitzRoy 能从伦敦把警报电传到沿海港口，"
  "那里会高高升起一套巧妙的旗语系统供过往船只识读。",
  "FitzRoy could telegraph warnings to ports on the coast.",
  "他把风暴警报电传到沿海港口。"),
 ("It attracted huge attention, including from Queen Victoria, who regularly sent messengers to FitzRoy's "
  "office to get a forecast for the sea crossing over the Solent to an island which she liked to visit off "
  "the south coast of England.",
  "它引起了巨大关注，包括来自维多利亚女王的关注；她经常派信使去索取穿越索伦特海峡、"
  "前往英格兰南岸外一座她喜欢造访的岛屿的天气预报。",
  "Queen Victoria regularly sent messengers to get a forecast.",
  "女王常派人来要预报。"),
 ("It is indisputable that FitzRoy was way ahead of his time, but it is only in recent years that he has "
  "been recognised as a towering figure in meteorology, with the honour of an area of sea being given his "
  "name in the shipping forecast.",
  "毫无疑问，FitzRoy 远远走在时代前面，但直到近些年他才被公认为气象学中的杰出人物，"
  "并获得了以他的名字命名一片海域的殊荣。",
  "It is only in recent years that he has been recognised as a towering figure.",
  "他直到近年才被认可。"),
],
}
